// =========================================================================
// BETTER_ANSH DASHBOARD - V3 DATA ENGINE
// =========================================================================

// TEAMS CONFIG
const TEAMS = {
  a: { name: "Team Alpha", short: "T-A", members: ["godxankit", "better_ansh", "adavya2193", "ansh gamer1988", "bettet_ansh"] },
  b: { name: "Team Beta", short: "T-B", members: ["kunal2010", "nitish_gamer45", "harshisop13", "deadly_kunal", "harsh"] }
};

function getTeam(name) {
  let lower = name.toLowerCase().replace('.', '');
  return TEAMS.b.members.includes(lower) ? 'b' : 'a';
}

const RAW_PLAYERS = [
  {
    "name": ".Harshisop13",
    "uuid": "00000000-0000-0000-0009-01f39b4bb6e8",
    "stats": {
      "minecraft:dropped": {
        "minecraft:cooked_chicken": 1,
        "minecraft:iron_axe": 1,
        "minecraft:iron_shovel": 1,
        "minecraft:iron_helmet": 1,
        "minecraft:iron_chestplate": 1,
        "minecraft:copper_ingot": 2,
        "minecraft:birch_planks": 4,
        "minecraft:leaf_litter": 30,
        "minecraft:iron_leggings": 1,
        "minecraft:clay_ball": 8,
        "minecraft:iron_sword": 1,
        "minecraft:dirt": 25,
        "minecraft:copper_chestplate": 1,
        "minecraft:wheat_seeds": 9,
        "minecraft:cooked_mutton": 36,
        "minecraft:iron_boots": 1,
        "minecraft:iron_pickaxe": 1,
        "minecraft:salmon_bucket": 1
      },
      "minecraft:crafted": {
        "minecraft:stone_sword": 1,
        "minecraft:copper_boots": 1,
        "minecraft:polished_deepslate_stairs": 75,
        "minecraft:cooked_chicken": 8,
        "minecraft:birch_planks": 124,
        "minecraft:stone_pickaxe": 1,
        "minecraft:cooked_mutton": 17,
        "minecraft:iron_chestplate": 1,
        "minecraft:iron_boots": 3,
        "minecraft:stick": 32,
        "minecraft:cooked_beef": 9,
        "minecraft:copper_chestplate": 1,
        "minecraft:oak_slab": 126,
        "minecraft:cooked_porkchop": 25,
        "minecraft:iron_helmet": 2,
        "minecraft:diamond_axe": 1,
        "minecraft:diamond_pickaxe": 1,
        "minecraft:chest": 13,
        "minecraft:diamond_sword": 1,
        "minecraft:air": 0,
        "minecraft:paper": 3,
        "minecraft:bucket": 1,
        "minecraft:bone_meal": 12,
        "minecraft:furnace": 3,
        "minecraft:oak_stairs": 96,
        "minecraft:iron_ingot": 116,
        "minecraft:copper_ingot": 48,
        "minecraft:red_dye": 1,
        "minecraft:crafting_table": 1,
        "minecraft:wolf_armor": 2,
        "minecraft:brush": 13,
        "minecraft:torch": 20,
        "minecraft:birch_slab": 54,
        "minecraft:polished_deepslate_slab": 24,
        "minecraft:stone_axe": 1,
        "minecraft:copper_helmet": 1,
        "minecraft:oak_planks": 300,
        "minecraft:spruce_planks": 36,
        "minecraft:diamond_spear": 1,
        "minecraft:iron_pickaxe": 1,
        "minecraft:iron_shovel": 6,
        "minecraft:iron_sword": 1,
        "minecraft:fishing_rod": 1,
        "minecraft:iron_axe": 1,
        "minecraft:iron_leggings": 2
      },
      "minecraft:used": {
        "minecraft:stone_axe": 108,
        "minecraft:diamond_sword": 59,
        "minecraft:diamond_shovel": 292,
        "minecraft:birch_planks": 1,
        "minecraft:water_bucket": 3,
        "minecraft:bone_meal": 12,
        "minecraft:diamond_pickaxe": 300,
        "minecraft:cooked_mutton": 2,
        "minecraft:furnace": 6,
        "minecraft:cooked_porkchop": 34,
        "minecraft:torch": 8,
        "minecraft:dirt": 345,
        "minecraft:fishing_rod": 2,
        "minecraft:iron_shovel": 1261,
        "minecraft:sand": 1,
        "minecraft:salmon_bucket": 1,
        "minecraft:stone_sword": 56,
        "minecraft:dark_oak_sapling": 1,
        "minecraft:polished_deepslate_stairs": 58,
        "minecraft:oak_log": 46,
        "minecraft:cobblestone": 69,
        "minecraft:oak_stairs": 13,
        "minecraft:polished_deepslate_slab": 27,
        "minecraft:diamond_axe": 540,
        "minecraft:stripped_oak_log": 29,
        "minecraft:bucket": 5,
        "minecraft:crafting_table": 2,
        "minecraft:chest": 13,
        "minecraft:oak_planks": 115,
        "minecraft:spruce_sapling": 35,
        "minecraft:egg": 1,
        "minecraft:white_bed": 2,
        "minecraft:stone_pickaxe": 114
      },
      "minecraft:killed_by": {
        "minecraft:zombie": 1
      },
      "minecraft:custom": {
        "minecraft:time_since_rest": 60659,
        "minecraft:leave_game": 9,
        "minecraft:damage_taken": 1954,
        "minecraft:mob_kills": 68,
        "minecraft:time_since_death": 305254,
        "minecraft:interact_with_furnace": 102,
        "minecraft:sleep_in_bed": 12,
        "minecraft:swim_one_cm": 79464,
        "minecraft:total_world_time": 306101,
        "minecraft:crouch_one_cm": 11479,
        "minecraft:deaths": 1,
        "minecraft:climb_one_cm": 100,
        "minecraft:interact_with_stonecutter": 5,
        "minecraft:fish_caught": 1,
        "minecraft:enchant_item": 2,
        "minecraft:interact_with_crafting_table": 32,
        "minecraft:walk_one_cm": 723515,
        "minecraft:walk_under_water_one_cm": 9247,
        "minecraft:damage_dealt": 6471,
        "minecraft:play_time": 306101,
        "minecraft:jump": 4916,
        "minecraft:drop": 25,
        "minecraft:bell_ring": 23,
        "minecraft:sprint_one_cm": 582603,
        "minecraft:open_chest": 104,
        "minecraft:fall_one_cm": 140669,
        "minecraft:fly_one_cm": 1064167,
        "minecraft:walk_on_water_one_cm": 43234,
        "minecraft:sneak_time": 5550
      },
      "minecraft:picked_up": {
        "minecraft:spruce_sapling": 54,
        "minecraft:iron_block": 4,
        "minecraft:cobblestone": 376,
        "minecraft:polished_deepslate_slab": 9,
        "minecraft:white_bed": 3,
        "minecraft:stripped_oak_log": 29,
        "minecraft:sugar_cane": 27,
        "minecraft:leather": 18,
        "minecraft:bone": 10,
        "minecraft:salmon_bucket": 1,
        "minecraft:gold_nugget": 16,
        "minecraft:diamond_shovel": 1,
        "minecraft:cooked_mutton": 29,
        "minecraft:clay_ball": 8,
        "minecraft:cod": 1,
        "minecraft:armadillo_scute": 8,
        "minecraft:diamond": 14,
        "minecraft:dark_oak_sapling": 2,
        "minecraft:porkchop": 38,
        "minecraft:stick": 35,
        "minecraft:chicken": 11,
        "minecraft:gold_block": 2,
        "minecraft:cooked_porkchop": 59,
        "minecraft:arrow": 1,
        "minecraft:iron_axe": 1,
        "minecraft:iron_ingot": 37,
        "minecraft:raw_iron": 6,
        "minecraft:mutton": 19,
        "minecraft:iron_chestplate": 1,
        "minecraft:dirt": 1312,
        "minecraft:brown_wool": 1,
        "minecraft:lodestone": 2,
        "minecraft:spruce_log": 334,
        "minecraft:polished_deepslate": 112,
        "minecraft:oak_stairs": 12,
        "minecraft:leaf_litter": 304,
        "minecraft:coal": 103,
        "minecraft:oak_log": 261,
        "minecraft:sand": 83,
        "minecraft:birch_planks": 5,
        "minecraft:birch_log": 45,
        "minecraft:furnace": 3,
        "minecraft:wheat_seeds": 21,
        "minecraft:egg": 17,
        "minecraft:pink_wool": 1,
        "minecraft:birch_sapling": 1,
        "minecraft:poppy": 2,
        "minecraft:cooked_beef": 52,
        "minecraft:feather": 9,
        "minecraft:white_wool": 9,
        "minecraft:oak_planks": 3,
        "minecraft:crafting_table": 2,
        "minecraft:copper_chestplate": 1,
        "minecraft:raw_copper": 48,
        "minecraft:oak_sapling": 5,
        "minecraft:rotten_flesh": 1,
        "minecraft:beef": 29,
        "minecraft:polished_deepslate_stairs": 1,
        "minecraft:apple": 2,
        "minecraft:string": 1,
        "minecraft:sandstone": 2,
        "minecraft:gray_wool": 1
      },
      "minecraft:killed": {
        "minecraft:zombie": 1,
        "minecraft:pillager": 1,
        "minecraft:horse": 6,
        "minecraft:chicken": 12,
        "minecraft:sheep": 17,
        "minecraft:pig": 14,
        "minecraft:cow": 14,
        "minecraft:wolf": 1,
        "minecraft:spider": 1
      },
      "minecraft:broken": {
        "minecraft:iron_shovel": 4,
        "minecraft:brush": 2
      },
      "minecraft:mined": {
        "minecraft:spruce_log": 335,
        "minecraft:dandelion": 1,
        "minecraft:coal_ore": 103,
        "minecraft:oak_planks": 1,
        "minecraft:cobblestone": 1,
        "minecraft:spruce_sapling": 4,
        "minecraft:sugar_cane": 19,
        "minecraft:white_bed": 3,
        "minecraft:short_grass": 77,
        "minecraft:polished_deepslate_stairs": 2,
        "minecraft:oak_leaves": 13,
        "minecraft:furnace": 3,
        "minecraft:clay": 2,
        "minecraft:crafting_table": 2,
        "minecraft:birch_log": 45,
        "minecraft:leaf_litter": 34,
        "minecraft:polished_deepslate_slab": 11,
        "minecraft:stripped_oak_log": 29,
        "minecraft:copper_ore": 14,
        "minecraft:sandstone": 2,
        "minecraft:oak_stairs": 13,
        "minecraft:dirt": 474,
        "minecraft:birch_leaves": 5,
        "minecraft:grass_block": 899,
        "minecraft:dark_oak_sapling": 2,
        "minecraft:spruce_leaves": 17,
        "minecraft:sand": 107,
        "minecraft:poppy": 1,
        "minecraft:oak_log": 76,
        "minecraft:birch_planks": 1,
        "minecraft:iron_ore": 3,
        "minecraft:stone": 264
      }
    }
  },
  {
    "name": "Player_000000",
    "uuid": "00000000-0000-0000-0009-01fde9be7525",
    "stats": {
      "minecraft:killed_by": {
        "minecraft:skeleton": 6
      },
      "minecraft:used": {
        "minecraft:iron_axe": 20,
        "minecraft:salmon_bucket": 1,
        "minecraft:iron_leggings": 2,
        "minecraft:cobbled_deepslate": 33,
        "minecraft:iron_pickaxe": 278,
        "minecraft:andesite": 2,
        "minecraft:iron_sword": 149,
        "minecraft:cobblestone": 60,
        "minecraft:water_bucket": 13,
        "minecraft:diamond_pickaxe": 21,
        "minecraft:glass": 1,
        "minecraft:bucket": 14,
        "minecraft:crafting_table": 2,
        "minecraft:iron_helmet": 1,
        "minecraft:iron_chestplate": 2,
        "minecraft:oak_planks": 4,
        "minecraft:furnace": 1,
        "minecraft:cooked_porkchop": 21,
        "minecraft:white_bed": 7,
        "minecraft:torch": 70,
        "minecraft:sugar_cane": 13,
        "minecraft:dirt": 1,
        "minecraft:iron_boots": 1
      },
      "minecraft:broken": {
        "minecraft:iron_pickaxe": 1
      },
      "minecraft:crafted": {
        "minecraft:furnace": 1,
        "minecraft:iron_ingot": 42,
        "minecraft:glass": 28,
        "minecraft:iron_boots": 1,
        "minecraft:iron_chestplate": 1,
        "minecraft:crafting_table": 1,
        "minecraft:torch": 68,
        "minecraft:stick": 24,
        "minecraft:oak_planks": 20,
        "minecraft:cooked_porkchop": 19,
        "minecraft:iron_helmet": 1,
        "minecraft:iron_pickaxe": 2,
        "minecraft:iron_sword": 1,
        "minecraft:iron_leggings": 1
      },
      "minecraft:custom": {
        "minecraft:time_since_rest": 2758,
        "minecraft:leave_game": 2,
        "minecraft:damage_taken": 3217,
        "minecraft:mob_kills": 24,
        "minecraft:time_since_death": 92268,
        "minecraft:interact_with_brewingstand": 1,
        "minecraft:interact_with_furnace": 30,
        "minecraft:sleep_in_bed": 5,
        "minecraft:total_world_time": 105469,
        "minecraft:swim_one_cm": 4575,
        "minecraft:crouch_one_cm": 11276,
        "minecraft:deaths": 6,
        "minecraft:interact_with_crafting_table": 12,
        "minecraft:walk_one_cm": 207646,
        "minecraft:walk_under_water_one_cm": 9512,
        "minecraft:play_time": 105469,
        "minecraft:damage_dealt": 4263,
        "minecraft:jump": 1800,
        "minecraft:drop": 2,
        "minecraft:sprint_one_cm": 229940,
        "minecraft:open_chest": 17,
        "minecraft:fall_one_cm": 57311,
        "minecraft:fly_one_cm": 252122,
        "minecraft:walk_on_water_one_cm": 18204,
        "minecraft:sneak_time": 8646,
        "minecraft:interact_with_grindstone": 1
      },
      "minecraft:killed": {
        "minecraft:zombie": 2,
        "minecraft:donkey": 1,
        "minecraft:horse": 2,
        "minecraft:skeleton": 1,
        "minecraft:creeper": 2,
        "minecraft:enderman": 3,
        "minecraft:pig": 11,
        "minecraft:cow": 2
      },
      "minecraft:dropped": {
        "minecraft:diamond_pickaxe": 2
      },
      "minecraft:picked_up": {
        "minecraft:dirt": 1,
        "minecraft:cobblestone": 68,
        "minecraft:white_bed": 7,
        "minecraft:gravel": 1,
        "minecraft:sugar_cane": 13,
        "minecraft:leather": 6,
        "minecraft:torch": 23,
        "minecraft:bone": 1,
        "minecraft:diamond_pickaxe": 2,
        "minecraft:dripstone_block": 1,
        "minecraft:iron_boots": 1,
        "minecraft:water_bucket": 4,
        "minecraft:coal": 153,
        "minecraft:oak_log": 53,
        "minecraft:furnace": 1,
        "minecraft:diamond": 7,
        "minecraft:iron_sword": 3,
        "minecraft:granite": 7,
        "minecraft:iron_pickaxe": 1,
        "minecraft:lapis_lazuli": 34,
        "minecraft:glow_ink_sac": 7,
        "minecraft:porkchop": 20,
        "minecraft:iron_leggings": 2,
        "minecraft:diorite": 1,
        "minecraft:oak_planks": 49,
        "minecraft:golden_chestplate": 2,
        "minecraft:cooked_porkchop": 50,
        "minecraft:crafting_table": 4,
        "minecraft:iron_ingot": 46,
        "minecraft:rotten_flesh": 2,
        "minecraft:raw_iron": 75,
        "minecraft:beef": 2,
        "minecraft:cobbled_deepslate": 47,
        "minecraft:andesite": 8,
        "minecraft:pointed_dripstone": 13,
        "minecraft:ender_pearl": 1,
        "minecraft:obsidian": 19,
        "minecraft:golden_leggings": 2,
        "minecraft:gunpowder": 2,
        "minecraft:iron_helmet": 3,
        "minecraft:iron_chestplate": 1
      },
      "minecraft:mined": {
        "minecraft:torch": 1,
        "minecraft:pointed_dripstone": 7,
        "minecraft:granite": 3,
        "minecraft:glass": 1,
        "minecraft:andesite": 8,
        "minecraft:coal_ore": 80,
        "minecraft:grass_block": 1,
        "minecraft:oak_planks": 7,
        "minecraft:cobblestone": 24,
        "minecraft:sugar_cane": 11,
        "minecraft:white_bed": 7,
        "minecraft:wall_torch": 2,
        "minecraft:diamond_ore": 2,
        "minecraft:deepslate": 52,
        "minecraft:furnace": 1,
        "minecraft:deepslate_lapis_ore": 2,
        "minecraft:deepslate_diamond_ore": 3,
        "minecraft:deepslate_iron_ore": 12,
        "minecraft:crafting_table": 2,
        "minecraft:obsidian": 19,
        "minecraft:iron_ore": 36,
        "minecraft:stone": 47,
        "minecraft:lapis_ore": 3
      }
    }
  },
  {
    "name": "Nitish_gamer45",
    "uuid": "1cd7e03e-a260-35ca-88d7-e776003394c7",
    "stats": {
      "minecraft:dropped": {
        "minecraft:copper_chestplate": 1,
        "minecraft:iron_axe": 1,
        "minecraft:cooked_mutton": 8
      },
      "minecraft:crafted": {
        "minecraft:smooth_stone": 4,
        "minecraft:deepslate_tile_stairs": 37,
        "minecraft:tuff_brick_stairs": 34,
        "minecraft:oak_planks": 160,
        "minecraft:cobblestone_stairs": 3
      },
      "minecraft:used": {
        "minecraft:iron_axe": 180,
        "minecraft:cobbled_deepslate": 98,
        "minecraft:apple": 2,
        "minecraft:cobblestone_slab": 32,
        "minecraft:iron_pickaxe": 170,
        "minecraft:cooked_chicken": 1,
        "minecraft:oak_log": 190,
        "minecraft:cobblestone": 215,
        "minecraft:cooked_mutton": 9,
        "minecraft:oak_planks": 68,
        "minecraft:copper_chestplate": 1,
        "minecraft:dirt": 12,
        "minecraft:oak_door": 2,
        "minecraft:iron_shovel": 239
      },
      "minecraft:custom": {
        "minecraft:interact_with_crafting_table": 11,
        "minecraft:time_since_rest": 7720,
        "minecraft:walk_one_cm": 258628,
        "minecraft:leave_game": 2,
        "minecraft:walk_under_water_one_cm": 977,
        "minecraft:mob_kills": 4,
        "minecraft:damage_taken": 339,
        "minecraft:play_time": 104539,
        "minecraft:damage_dealt": 815,
        "minecraft:jump": 712,
        "minecraft:time_since_death": 104539,
        "minecraft:drop": 10,
        "minecraft:interact_with_furnace": 18,
        "minecraft:sprint_one_cm": 223693,
        "minecraft:open_chest": 50,
        "minecraft:sleep_in_bed": 4,
        "minecraft:fall_one_cm": 12800,
        "minecraft:total_world_time": 104539,
        "minecraft:fly_one_cm": 131131,
        "minecraft:walk_on_water_one_cm": 1847,
        "minecraft:interact_with_stonecutter": 3
      },
      "minecraft:picked_up": {
        "minecraft:dirt": 200,
        "minecraft:cobblestone": 238,
        "minecraft:iron_shovel": 1,
        "minecraft:stripped_oak_log": 2,
        "minecraft:leather": 4,
        "minecraft:iron_boots": 1,
        "minecraft:cooked_mutton": 27,
        "minecraft:oak_log": 266,
        "minecraft:iron_sword": 1,
        "minecraft:wheat_seeds": 13,
        "minecraft:oak_door": 1,
        "minecraft:iron_pickaxe": 1,
        "minecraft:egg": 2,
        "minecraft:iron_leggings": 1,
        "minecraft:stick": 6,
        "minecraft:iron_axe": 2,
        "minecraft:copper_chestplate": 1,
        "minecraft:oak_sapling": 2,
        "minecraft:cooked_chicken": 1,
        "minecraft:beef": 5,
        "minecraft:cobbled_deepslate": 96,
        "minecraft:cobblestone_slab": 195,
        "minecraft:copper_ingot": 2,
        "minecraft:iron_helmet": 1,
        "minecraft:iron_chestplate": 1
      },
      "minecraft:killed": {
        "minecraft:pillager": 1,
        "minecraft:horse": 1,
        "minecraft:cow": 2
      },
      "minecraft:mined": {
        "minecraft:short_grass": 57,
        "minecraft:cobblestone_slab": 1,
        "minecraft:dirt": 12,
        "minecraft:oak_log": 148,
        "minecraft:stripped_oak_log": 2,
        "minecraft:grass_block": 186,
        "minecraft:cobblestone": 61,
        "minecraft:cobbled_deepslate": 96,
        "minecraft:oak_door": 1
      }
    }
  },
  {
    "name": "kunal2010",
    "uuid": "2ef7d0fb-36a6-3bc5-8bb1-b417ebdcf928",
    "stats": {
      "minecraft:dropped": {
        "minecraft:cobblestone": 311,
        "minecraft:oak_planks": 57,
        "minecraft:porkchop": 4,
        "minecraft:oxeye_daisy": 1,
        "minecraft:cobbled_deepslate": 266,
        "minecraft:poppy": 1,
        "minecraft:iron_ingot": 12,
        "minecraft:cobblestone_slab": 192,
        "minecraft:dripstone_block": 11,
        "minecraft:diamond": 24,
        "minecraft:stone_pickaxe": 2,
        "minecraft:azure_bluet": 2,
        "minecraft:cooked_chicken": 4,
        "minecraft:oak_log": 287,
        "minecraft:diamond_pickaxe": 1,
        "minecraft:iron_block": 4,
        "minecraft:dandelion": 8,
        "minecraft:chicken": 2,
        "minecraft:furnace": 1,
        "minecraft:string": 4,
        "minecraft:diamond_sword": 3,
        "minecraft:stick": 10,
        "minecraft:phantom_membrane": 1,
        "minecraft:spruce_sapling": 4,
        "minecraft:arrow": 3,
        "minecraft:crafting_table": 1,
        "minecraft:polished_deepslate": 112,
        "minecraft:wooden_axe": 1,
        "minecraft:gunpowder": 1,
        "minecraft:stone_axe": 2,
        "minecraft:iron_pickaxe": 1,
        "minecraft:mutton": 5,
        "minecraft:cooked_porkchop": 11
      },
      "minecraft:used": {
        "minecraft:stone_axe": 91,
        "minecraft:diamond_block": 13,
        "minecraft:oak_trapdoor": 4,
        "minecraft:leaf_litter": 26,
        "minecraft:stone_slab": 1,
        "minecraft:shield": 27,
        "minecraft:iron_pickaxe": 250,
        "minecraft:polished_deepslate": 83,
        "minecraft:iron_block": 6,
        "minecraft:diamond_sword": 234,
        "minecraft:golden_carrot": 3,
        "minecraft:pink_wool": 1,
        "minecraft:wooden_axe": 5,
        "minecraft:diamond_pickaxe": 1850,
        "minecraft:cooked_mutton": 3,
        "minecraft:bookshelf": 2,
        "minecraft:glass": 26,
        "minecraft:glass_pane": 32,
        "minecraft:cooked_porkchop": 18,
        "minecraft:blast_furnace": 3,
        "minecraft:brewing_stand": 4,
        "minecraft:polished_deepslate_stairs": 106,
        "minecraft:diorite": 27,
        "minecraft:wooden_pickaxe": 7,
        "minecraft:copper_block": 1,
        "minecraft:oak_log": 65,
        "minecraft:cobblestone": 160,
        "minecraft:polished_deepslate_slab": 138,
        "minecraft:stonecutter": 3,
        "minecraft:grindstone": 4,
        "minecraft:diamond_axe": 831,
        "minecraft:stripped_oak_log": 3,
        "minecraft:crafting_table": 21,
        "minecraft:white_bed": 11,
        "minecraft:stone_pickaxe": 94,
        "minecraft:pointed_dripstone": 3,
        "minecraft:oak_door": 3,
        "minecraft:cobbled_deepslate": 85,
        "minecraft:diamond_shovel": 527,
        "minecraft:pumpkin": 1,
        "minecraft:rotten_flesh": 7,
        "minecraft:water_bucket": 91,
        "minecraft:bone_meal": 3,
        "minecraft:dark_oak_planks": 14,
        "minecraft:furnace": 4,
        "minecraft:torch": 59,
        "minecraft:bread": 15,
        "minecraft:dirt": 29,
        "minecraft:obsidian": 10,
        "minecraft:chicken": 1,
        "minecraft:dark_oak_sapling": 1,
        "minecraft:cobblestone_slab": 282,
        "minecraft:cooked_chicken": 8,
        "minecraft:gray_wool": 1,
        "minecraft:oak_stairs": 22,
        "minecraft:shears": 1,
        "minecraft:cooked_beef": 10,
        "minecraft:flint_and_steel": 1,
        "minecraft:bucket": 92,
        "minecraft:dark_oak_boat": 1,
        "minecraft:chest": 62,
        "minecraft:enchanting_table": 1,
        "minecraft:oak_planks": 34,
        "minecraft:sugar_cane": 44,
        "minecraft:ender_pearl": 1,
        "minecraft:smooth_stone_slab": 26
      },
      "minecraft:crafted": {
        "minecraft:diamond_boots": 1,
        "minecraft:gold_ingot": 24,
        "minecraft:book": 8,
        "minecraft:iron_chestplate": 1,
        "minecraft:glass_pane": 32,
        "minecraft:leather_leggings": 3,
        "minecraft:stick": 100,
        "minecraft:cooked_porkchop": 19,
        "minecraft:diamond_axe": 2,
        "minecraft:iron_block": 6,
        "minecraft:diamond_pickaxe": 4,
        "minecraft:chest": 40,
        "minecraft:bookshelf": 2,
        "minecraft:light_gray_dye": 1,
        "minecraft:air": 0,
        "minecraft:bucket": 1,
        "minecraft:flint_and_steel": 1,
        "minecraft:bone_meal": 3,
        "minecraft:oak_stairs": 20,
        "minecraft:dark_oak_planks": 268,
        "minecraft:lapis_block": 11,
        "minecraft:diamond_shovel": 1,
        "minecraft:glass": 59,
        "minecraft:cobblestone_slab": 612,
        "minecraft:oak_trapdoor": 2,
        "minecraft:oak_planks": 516,
        "minecraft:enchanting_table": 1,
        "minecraft:shears": 1,
        "minecraft:polished_deepslate": 192,
        "minecraft:polished_deepslate_stairs": 44,
        "minecraft:yellow_dye": 1,
        "minecraft:cooked_chicken": 6,
        "minecraft:stone_pickaxe": 2,
        "minecraft:cooked_mutton": 6,
        "minecraft:iron_boots": 1,
        "minecraft:dark_oak_boat": 1,
        "minecraft:smooth_stone": 28,
        "minecraft:white_wool": 1,
        "minecraft:wooden_pickaxe": 2,
        "minecraft:cooked_beef": 5,
        "minecraft:diamond": 72,
        "minecraft:stonecutter": 1,
        "minecraft:blue_dye": 1,
        "minecraft:tuff_bricks": 8,
        "minecraft:diamond_chestplate": 1,
        "minecraft:diamond_sword": 2,
        "minecraft:polished_tuff": 8,
        "minecraft:emerald": 1,
        "minecraft:wheat": 82,
        "minecraft:raw_iron": 9,
        "minecraft:paper": 24,
        "minecraft:iron_ingot": 38,
        "minecraft:copper_ingot": 11,
        "minecraft:diamond_helmet": 1,
        "minecraft:bread": 36,
        "minecraft:stone": 35,
        "minecraft:crafting_table": 17,
        "minecraft:diamond_leggings": 1,
        "minecraft:torch": 84,
        "minecraft:white_bed": 4,
        "minecraft:magenta_dye": 1,
        "minecraft:stone_axe": 1,
        "minecraft:saddle": 1,
        "minecraft:spruce_planks": 28,
        "minecraft:iron_pickaxe": 1,
        "minecraft:diamond_block": 8,
        "minecraft:copper_block": 1,
        "minecraft:iron_leggings": 1,
        "minecraft:golden_apple": 3
      },
      "minecraft:killed_by": {
        "minecraft:player": 1,
        "minecraft:creeper": 1
      },
      "minecraft:custom": {
        "minecraft:time_since_rest": 34841,
        "minecraft:talked_to_villager": 23,
        "minecraft:leave_game": 5,
        "minecraft:damage_taken": 2890,
        "minecraft:mob_kills": 86,
        "minecraft:boat_one_cm": 40385,
        "minecraft:time_since_death": 63726,
        "minecraft:interact_with_brewingstand": 1,
        "minecraft:interact_with_furnace": 140,
        "minecraft:sleep_in_bed": 13,
        "minecraft:swim_one_cm": 58170,
        "minecraft:total_world_time": 454847,
        "minecraft:crouch_one_cm": 39514,
        "minecraft:climb_one_cm": 1265,
        "minecraft:deaths": 2,
        "minecraft:interact_with_stonecutter": 7,
        "minecraft:traded_with_villager": 2,
        "minecraft:damage_blocked_by_shield": 4546,
        "minecraft:interact_with_crafting_table": 100,
        "minecraft:walk_one_cm": 1057877,
        "minecraft:walk_under_water_one_cm": 11878,
        "minecraft:damage_dealt": 13036,
        "minecraft:play_time": 454847,
        "minecraft:jump": 8119,
        "minecraft:drop": 394,
        "minecraft:bell_ring": 12,
        "minecraft:sprint_one_cm": 805235,
        "minecraft:open_chest": 347,
        "minecraft:fall_one_cm": 212253,
        "minecraft:fly_one_cm": 1668208,
        "minecraft:walk_on_water_one_cm": 56257,
        "minecraft:sneak_time": 18594,
        "minecraft:interact_with_blast_furnace": 6,
        "minecraft:interact_with_grindstone": 1
      },
      "minecraft:picked_up": {
        "minecraft:smooth_stone_slab": 13,
        "minecraft:brewing_stand": 4,
        "minecraft:cobblestone": 920,
        "minecraft:glass": 21,
        "minecraft:flint": 11,
        "minecraft:sugar_cane": 82,
        "minecraft:redstone": 55,
        "minecraft:bone": 12,
        "minecraft:diamond_shovel": 1,
        "minecraft:diamond": 131,
        "minecraft:white_banner": 1,
        "minecraft:granite": 31,
        "minecraft:dark_oak_sapling": 1,
        "minecraft:book": 1,
        "minecraft:salmon": 2,
        "minecraft:gold_block": 4,
        "minecraft:arrow": 14,
        "minecraft:iron_ingot": 11,
        "minecraft:dark_oak_planks": 190,
        "minecraft:hay_block": 12,
        "minecraft:raw_gold": 39,
        "minecraft:dandelion": 9,
        "minecraft:mutton": 33,
        "minecraft:golden_carrot": 1,
        "minecraft:diamond_leggings": 1,
        "minecraft:iron_chestplate": 1,
        "minecraft:dirt": 263,
        "minecraft:brown_wool": 2,
        "minecraft:stonecutter": 2,
        "minecraft:diamond_helmet": 1,
        "minecraft:azure_bluet": 2,
        "minecraft:torch": 1,
        "minecraft:diamond_pickaxe": 2,
        "minecraft:dripstone_block": 23,
        "minecraft:spruce_log": 7,
        "minecraft:oxeye_daisy": 3,
        "minecraft:oak_stairs": 9,
        "minecraft:coal": 70,
        "minecraft:oak_log": 461,
        "minecraft:sand": 108,
        "minecraft:furnace": 5,
        "minecraft:oak_door": 3,
        "minecraft:wheat_seeds": 85,
        "minecraft:iron_pickaxe": 3,
        "minecraft:iron_leggings": 1,
        "minecraft:diamond_sword": 3,
        "minecraft:birch_sapling": 2,
        "minecraft:poppy": 2,
        "minecraft:cooked_beef": 10,
        "minecraft:white_wool": 16,
        "minecraft:feather": 1,
        "minecraft:red_mushroom": 1,
        "minecraft:blast_furnace": 3,
        "minecraft:andesite": 62,
        "minecraft:ender_pearl": 3,
        "minecraft:string": 8,
        "minecraft:raw_iron_block": 1,
        "minecraft:obsidian": 43,
        "minecraft:cornflower": 2,
        "minecraft:iron_helmet": 1,
        "minecraft:diamond_axe": 2,
        "minecraft:spruce_sapling": 6,
        "minecraft:iron_block": 4,
        "minecraft:polished_deepslate_slab": 13,
        "minecraft:white_bed": 8,
        "minecraft:stripped_oak_log": 3,
        "minecraft:leather": 36,
        "minecraft:stone_slab": 1,
        "minecraft:brown_mushroom": 4,
        "minecraft:water_bucket": 1,
        "minecraft:stone_pickaxe": 3,
        "minecraft:wooden_axe": 3,
        "minecraft:glow_ink_sac": 7,
        "minecraft:porkchop": 26,
        "minecraft:oak_trapdoor": 2,
        "minecraft:stick": 25,
        "minecraft:black_wool": 1,
        "minecraft:chicken": 5,
        "minecraft:diamond_boots": 1,
        "minecraft:cooked_porkchop": 23,
        "minecraft:iron_axe": 1,
        "minecraft:cooked_chicken": 2,
        "minecraft:grindstone": 4,
        "minecraft:raw_iron": 110,
        "minecraft:cobbled_deepslate": 1079,
        "minecraft:diamond_chestplate": 2,
        "minecraft:pointed_dripstone": 15,
        "minecraft:lapis_block": 11,
        "minecraft:allium": 1,
        "minecraft:pumpkin_seeds": 4,
        "minecraft:stone_axe": 3,
        "minecraft:wheat": 8,
        "minecraft:gunpowder": 2,
        "minecraft:chest": 22,
        "minecraft:gravel": 57,
        "minecraft:tuff": 107,
        "minecraft:polished_deepslate": 3,
        "minecraft:leaf_litter": 48,
        "minecraft:phantom_membrane": 3,
        "minecraft:grass_block": 3,
        "minecraft:birch_log": 12,
        "minecraft:shield": 3,
        "minecraft:lapis_lazuli": 70,
        "minecraft:pumpkin": 21,
        "minecraft:diamond_block": 17,
        "minecraft:dark_oak_log": 81,
        "minecraft:ominous_bottle": 1,
        "minecraft:diorite": 27,
        "minecraft:wooden_pickaxe": 1,
        "minecraft:oak_planks": 109,
        "minecraft:crafting_table": 4,
        "minecraft:raw_copper": 8,
        "minecraft:oak_sapling": 22,
        "minecraft:beef": 13,
        "minecraft:rotten_flesh": 11,
        "minecraft:polished_deepslate_stairs": 7,
        "minecraft:apple": 5,
        "minecraft:cobblestone_slab": 273,
        "minecraft:iron_nugget": 12,
        "minecraft:paper": 9,
        "minecraft:gray_wool": 1
      },
      "minecraft:killed": {
        "minecraft:pillager": 9,
        "minecraft:skeleton": 8,
        "minecraft:iron_golem": 1,
        "minecraft:pig": 13,
        "minecraft:spider": 2,
        "minecraft:llama": 1,
        "minecraft:salmon": 3,
        "minecraft:horse": 4,
        "minecraft:zombie": 5,
        "minecraft:donkey": 1,
        "minecraft:chicken": 5,
        "minecraft:enderman": 3,
        "minecraft:sheep": 20,
        "minecraft:cow": 8,
        "minecraft:wolf": 1
      },
      "minecraft:broken": {
        "minecraft:stone_axe": 1,
        "minecraft:iron_pickaxe": 1,
        "minecraft:diamond_pickaxe": 1
      },
      "minecraft:mined": {
        "minecraft:spruce_log": 8,
        "minecraft:chest": 22,
        "minecraft:pumpkin": 21,
        "minecraft:gravel": 58,
        "minecraft:short_grass": 573,
        "minecraft:red_mushroom": 1,
        "minecraft:brown_mushroom": 2,
        "minecraft:crafting_table": 3,
        "minecraft:birch_log": 12,
        "minecraft:deepslate_redstone_ore": 3,
        "minecraft:leaf_litter": 6,
        "minecraft:oxeye_daisy": 3,
        "minecraft:polished_deepslate_slab": 7,
        "minecraft:stripped_oak_log": 3,
        "minecraft:obsidian": 39,
        "minecraft:dark_oak_planks": 1,
        "minecraft:copper_ore": 1,
        "minecraft:raw_iron_block": 1,
        "minecraft:grindstone": 4,
        "minecraft:gold_ore": 1,
        "minecraft:birch_leaves": 11,
        "minecraft:andesite": 31,
        "minecraft:smooth_stone_slab": 13,
        "minecraft:blast_furnace": 3,
        "minecraft:deepslate_gold_ore": 5,
        "minecraft:gold_block": 2,
        "minecraft:mushroom_stem": 2,
        "minecraft:dark_oak_leaves": 13,
        "minecraft:deepslate_diamond_ore": 113,
        "minecraft:poppy": 1,
        "minecraft:deepslate_lapis_ore": 4,
        "minecraft:deepslate_iron_ore": 102,
        "minecraft:iron_block": 4,
        "minecraft:dripstone_block": 1,
        "minecraft:allium": 1,
        "minecraft:iron_ore": 10,
        "minecraft:stone": 643,
        "minecraft:dark_oak_log": 76,
        "minecraft:granite": 16,
        "minecraft:bush": 16,
        "minecraft:dandelion": 4,
        "minecraft:coal_ore": 67,
        "minecraft:diorite": 27,
        "minecraft:oak_planks": 45,
        "minecraft:hay_block": 10,
        "minecraft:cobblestone": 145,
        "minecraft:sugar_cane": 68,
        "minecraft:oak_trapdoor": 2,
        "minecraft:white_bed": 7,
        "minecraft:diamond_block": 13,
        "minecraft:red_mushroom_block": 18,
        "minecraft:polished_deepslate_stairs": 2,
        "minecraft:oak_leaves": 102,
        "minecraft:furnace": 4,
        "minecraft:polished_deepslate": 3,
        "minecraft:brewing_stand": 4,
        "minecraft:tall_grass": 88,
        "minecraft:pointed_dripstone": 9,
        "minecraft:tall_seagrass": 1,
        "minecraft:oak_stairs": 4,
        "minecraft:dirt": 27,
        "minecraft:grass_block": 210,
        "minecraft:spruce_leaves": 7,
        "minecraft:cobbled_deepslate": 8,
        "minecraft:tuff": 85,
        "minecraft:deepslate": 750,
        "minecraft:sand": 108,
        "minecraft:cobblestone_slab": 5,
        "minecraft:seagrass": 3,
        "minecraft:cornflower": 3,
        "minecraft:stonecutter": 2,
        "minecraft:oak_log": 452,
        "minecraft:lapis_ore": 6,
        "minecraft:oak_door": 2
      }
    }
  },
  {
    "name": "Harsh",
    "uuid": "41cae289-aab6-3d0e-ab10-4533b37cb8a0",
    "stats": {
      "minecraft:crafted": {
        "minecraft:stick": 12,
        "minecraft:wooden_axe": 1,
        "minecraft:oak_planks": 44,
        "minecraft:crafting_table": 1
      },
      "minecraft:used": {
        "minecraft:wooden_axe": 1,
        "minecraft:crafting_table": 1
      },
      "minecraft:custom": {
        "minecraft:interact_with_crafting_table": 1,
        "minecraft:time_since_rest": 6020,
        "minecraft:walk_one_cm": 4205,
        "minecraft:leave_game": 1,
        "minecraft:damage_taken": 150,
        "minecraft:play_time": 6020,
        "minecraft:jump": 84,
        "minecraft:time_since_death": 6020,
        "minecraft:drop": 8,
        "minecraft:sprint_one_cm": 10607,
        "minecraft:fall_one_cm": 2225,
        "minecraft:total_world_time": 6020,
        "minecraft:fly_one_cm": 18356,
        "minecraft:walk_on_water_one_cm": 904,
        "minecraft:crouch_one_cm": 152,
        "minecraft:sneak_time": 146
      },
      "minecraft:picked_up": {
        "minecraft:oak_log": 11,
        "minecraft:wooden_axe": 1,
        "minecraft:stick": 10,
        "minecraft:oak_planks": 31,
        "minecraft:crafting_table": 2
      },
      "minecraft:dropped": {
        "minecraft:crafting_table": 2,
        "minecraft:oak_planks": 62,
        "minecraft:wooden_axe": 2,
        "minecraft:stick": 20
      },
      "minecraft:mined": {
        "minecraft:short_grass": 1,
        "minecraft:crafting_table": 1,
        "minecraft:oak_log": 5
      }
    }
  },
  {
    "name": "Better_Ansh",
    "uuid": "93c37127-b993-3dbb-8005-865c96a3e98c",
    "stats": {
      "minecraft:broken": {
        "minecraft:iron_helmet": 1,
        "minecraft:shield": 1,
        "minecraft:diamond_axe": 1
      },
      "minecraft:dropped": {
        "minecraft:diamond_shovel": 1,
        "minecraft:iron_axe": 1,
        "minecraft:oak_planks": 6,
        "minecraft:iron_chestplate": 1,
        "minecraft:bone": 8,
        "minecraft:wheat_seeds": 6,
        "minecraft:iron_ingot": 69,
        "minecraft:sunflower": 1,
        "minecraft:diamond": 8,
        "minecraft:shield": 1,
        "minecraft:water_bucket": 1,
        "minecraft:oak_log": 53,
        "minecraft:dark_oak_sapling": 8,
        "minecraft:diamond_pickaxe": 1,
        "minecraft:dandelion": 2,
        "minecraft:diamond_sword": 1,
        "minecraft:stick": 1,
        "minecraft:phantom_membrane": 1,
        "minecraft:gunpowder": 1,
        "minecraft:wooden_axe": 1,
        "minecraft:netherrack": 1,
        "minecraft:cooked_mutton": 10,
        "minecraft:gray_wool": 2,
        "minecraft:cooked_porkchop": 18,
        "minecraft:salmon_bucket": 1
      },
      "minecraft:killed_by": {
        "minecraft:creeper": 2,
        "minecraft:zombie": 2
      },
      "minecraft:custom": {
        "minecraft:time_since_rest": 5019,
        "minecraft:leave_game": 8,
        "minecraft:damage_taken": 10216,
        "minecraft:mob_kills": 358,
        "minecraft:time_since_death": 290406,
        "minecraft:interact_with_furnace": 199,
        "minecraft:sleep_in_bed": 18,
        "minecraft:swim_one_cm": 219540,
        "minecraft:total_world_time": 673560,
        "minecraft:crouch_one_cm": 114255,
        "minecraft:deaths": 6,
        "minecraft:climb_one_cm": 275,
        "minecraft:player_kills": 1,
        "minecraft:damage_blocked_by_shield": 9128,
        "minecraft:interact_with_crafting_table": 102,
        "minecraft:walk_one_cm": 946845,
        "minecraft:walk_under_water_one_cm": 77096,
        "minecraft:damage_dealt": 37374,
        "minecraft:play_time": 673560,
        "minecraft:jump": 12077,
        "minecraft:drop": 49,
        "minecraft:sprint_one_cm": 1300793,
        "minecraft:open_chest": 272,
        "minecraft:inspect_hopper": 2,
        "minecraft:fall_one_cm": 394331,
        "minecraft:fly_one_cm": 2450161,
        "minecraft:walk_on_water_one_cm": 142908,
        "minecraft:sneak_time": 55383
      },
      "minecraft:used": {
        "minecraft:stone_axe": 64,
        "minecraft:oak_fence": 15,
        "minecraft:oak_trapdoor": 1,
        "minecraft:iron_axe": 23,
        "minecraft:shield": 60,
        "minecraft:iron_pickaxe": 169,
        "minecraft:spruce_stairs": 156,
        "minecraft:polished_deepslate": 1,
        "minecraft:iron_block": 1,
        "minecraft:diamond_sword": 226,
        "minecraft:diamond_pickaxe": 886,
        "minecraft:cooked_mutton": 56,
        "minecraft:glass": 13,
        "minecraft:glass_pane": 76,
        "minecraft:cooked_porkchop": 49,
        "minecraft:iron_shovel": 34,
        "minecraft:lava_bucket": 1,
        "minecraft:diorite": 6,
        "minecraft:black_wool": 5,
        "minecraft:oak_slab": 196,
        "minecraft:wooden_pickaxe": 20,
        "minecraft:spruce_door": 1,
        "minecraft:oak_log": 300,
        "minecraft:cobblestone": 75,
        "minecraft:diamond_chestplate": 2,
        "minecraft:hopper": 2,
        "minecraft:spruce_slab": 19,
        "minecraft:diamond_axe": 2432,
        "minecraft:crafting_table": 14,
        "minecraft:oak_fence_gate": 1,
        "minecraft:white_bed": 3,
        "minecraft:stone_pickaxe": 107,
        "minecraft:bow": 17,
        "minecraft:oak_door": 6,
        "minecraft:iron_leggings": 2,
        "minecraft:cobbled_deepslate": 121,
        "minecraft:diamond_shovel": 444,
        "minecraft:spruce_log": 4,
        "minecraft:birch_planks": 20,
        "minecraft:water_bucket": 154,
        "minecraft:dark_oak_planks": 5,
        "minecraft:furnace": 19,
        "minecraft:torch": 15,
        "minecraft:dirt": 341,
        "minecraft:black_bed": 3,
        "minecraft:dark_oak_slab": 17,
        "minecraft:spruce_planks": 39,
        "minecraft:cobblestone_slab": 38,
        "minecraft:birch_log": 1,
        "minecraft:cooked_chicken": 9,
        "minecraft:oak_stairs": 211,
        "minecraft:cooked_beef": 19,
        "minecraft:bucket": 155,
        "minecraft:chest": 9,
        "minecraft:iron_helmet": 1,
        "minecraft:oak_planks": 644,
        "minecraft:spruce_sapling": 31,
        "minecraft:brown_wool": 6,
        "minecraft:egg": 24,
        "minecraft:sugar_cane": 37
      },
      "minecraft:mined": {
        "minecraft:black_bed": 2,
        "minecraft:spruce_log": 176,
        "minecraft:chest": 3,
        "minecraft:netherrack": 3,
        "minecraft:oak_slab": 18,
        "minecraft:sunflower": 1,
        "minecraft:gravel": 72,
        "minecraft:short_grass": 176,
        "minecraft:spruce_planks": 5,
        "minecraft:crafting_table": 8,
        "minecraft:birch_log": 81,
        "minecraft:deepslate_redstone_ore": 86,
        "minecraft:leaf_litter": 30,
        "minecraft:oxeye_daisy": 1,
        "minecraft:black_wool": 2,
        "minecraft:obsidian": 5,
        "minecraft:dark_oak_planks": 5,
        "minecraft:raw_iron_block": 3,
        "minecraft:firefly_bush": 1,
        "minecraft:gold_ore": 20,
        "minecraft:birch_leaves": 5,
        "minecraft:andesite": 3,
        "minecraft:oak_fence": 2,
        "minecraft:dark_oak_slab": 3,
        "minecraft:deepslate_gold_ore": 48,
        "minecraft:gold_block": 2,
        "minecraft:dark_oak_leaves": 5,
        "minecraft:stone_brick_stairs": 1,
        "minecraft:deepslate_lapis_ore": 6,
        "minecraft:deepslate_diamond_ore": 58,
        "minecraft:deepslate_iron_ore": 170,
        "minecraft:iron_block": 3,
        "minecraft:dripstone_block": 10,
        "minecraft:birch_planks": 20,
        "minecraft:iron_ore": 43,
        "minecraft:stone": 212,
        "minecraft:granite": 23,
        "minecraft:dark_oak_log": 51,
        "minecraft:bush": 4,
        "minecraft:glass": 3,
        "minecraft:stone_slab": 1,
        "minecraft:dandelion": 3,
        "minecraft:coal_ore": 130,
        "minecraft:diorite": 27,
        "minecraft:oak_planks": 161,
        "minecraft:cobblestone": 39,
        "minecraft:hay_block": 15,
        "minecraft:sugar_cane": 269,
        "minecraft:white_bed": 3,
        "minecraft:bee_nest": 4,
        "minecraft:pink_tulip": 1,
        "minecraft:oak_leaves": 117,
        "minecraft:furnace": 11,
        "minecraft:polished_deepslate": 1,
        "minecraft:spruce_stairs": 18,
        "minecraft:rose_bush": 2,
        "minecraft:deepslate_copper_ore": 3,
        "minecraft:tall_grass": 56,
        "minecraft:pointed_dripstone": 1,
        "minecraft:oak_stairs": 40,
        "minecraft:dirt": 62,
        "minecraft:grass_block": 308,
        "minecraft:spruce_leaves": 57,
        "minecraft:cobbled_deepslate": 7,
        "minecraft:tuff": 39,
        "minecraft:deepslate": 178,
        "minecraft:sand": 109,
        "minecraft:spruce_slab": 3,
        "minecraft:cobblestone_slab": 1,
        "minecraft:oak_log": 1027,
        "minecraft:lapis_ore": 2,
        "minecraft:oak_door": 6
      },
      "minecraft:killed": {
        "minecraft:pillager": 2,
        "minecraft:slime": 7,
        "minecraft:skeleton": 7,
        "minecraft:iron_golem": 1,
        "minecraft:pig": 66,
        "minecraft:wandering_trader": 1,
        "minecraft:spider": 10,
        "minecraft:zombie": 22,
        "minecraft:horse": 15,
        "minecraft:trader_llama": 1,
        "minecraft:creeper": 6,
        "minecraft:zombie_villager": 1,
        "minecraft:chicken": 22,
        "minecraft:sheep": 98,
        "minecraft:cow": 65
      },
      "minecraft:picked_up": {
        "minecraft:cobblestone": 308,
        "minecraft:flint": 13,
        "minecraft:sugar_cane": 390,
        "minecraft:bone": 16,
        "minecraft:redstone": 547,
        "minecraft:rose_bush": 2,
        "minecraft:diamond_shovel": 1,
        "minecraft:cooked_mutton": 10,
        "minecraft:firefly_bush": 1,
        "minecraft:diamond": 78,
        "minecraft:slime_ball": 14,
        "minecraft:granite": 22,
        "minecraft:white_banner": 2,
        "minecraft:dark_oak_sapling": 16,
        "minecraft:ink_sac": 1,
        "minecraft:salmon": 1,
        "minecraft:gold_block": 2,
        "minecraft:bow": 2,
        "minecraft:arrow": 76,
        "minecraft:iron_ingot": 166,
        "minecraft:dark_oak_planks": 67,
        "minecraft:spruce_slab": 3,
        "minecraft:enchanted_golden_apple": 1,
        "minecraft:crossbow": 1,
        "minecraft:hay_block": 15,
        "minecraft:raw_gold": 99,
        "minecraft:golden_leggings": 1,
        "minecraft:dandelion": 4,
        "minecraft:mutton": 145,
        "minecraft:spruce_planks": 5,
        "minecraft:dirt": 509,
        "minecraft:brown_wool": 6,
        "minecraft:torch": 1,
        "minecraft:diamond_pickaxe": 4,
        "minecraft:dripstone_block": 17,
        "minecraft:spruce_log": 173,
        "minecraft:oak_stairs": 32,
        "minecraft:coal": 261,
        "minecraft:oak_log": 2264,
        "minecraft:oak_fence": 2,
        "minecraft:sand": 109,
        "minecraft:birch_planks": 20,
        "minecraft:furnace": 11,
        "minecraft:wheat_seeds": 39,
        "minecraft:black_bed": 2,
        "minecraft:oak_door": 7,
        "minecraft:iron_pickaxe": 5,
        "minecraft:golden_axe": 1,
        "minecraft:egg": 9,
        "minecraft:iron_leggings": 2,
        "minecraft:diamond_sword": 4,
        "minecraft:birch_sapling": 31,
        "minecraft:sunflower": 1,
        "minecraft:cooked_beef": 12,
        "minecraft:feather": 24,
        "minecraft:white_wool": 61,
        "minecraft:red_mushroom": 7,
        "minecraft:andesite": 2,
        "minecraft:string": 20,
        "minecraft:raw_iron_block": 3,
        "minecraft:obsidian": 15,
        "minecraft:iron_helmet": 2,
        "minecraft:dark_oak_slab": 3,
        "minecraft:diamond_axe": 1,
        "minecraft:spruce_sapling": 48,
        "minecraft:iron_block": 7,
        "minecraft:white_bed": 3,
        "minecraft:leather": 112,
        "minecraft:salmon_bucket": 1,
        "minecraft:lead": 3,
        "minecraft:water_bucket": 4,
        "minecraft:wooden_axe": 1,
        "minecraft:glow_ink_sac": 7,
        "minecraft:porkchop": 149,
        "minecraft:stick": 512,
        "minecraft:black_wool": 13,
        "minecraft:chicken": 25,
        "minecraft:diamond_boots": 2,
        "minecraft:cooked_porkchop": 42,
        "minecraft:iron_axe": 1,
        "minecraft:cooked_chicken": 4,
        "minecraft:raw_iron": 268,
        "minecraft:cobbled_deepslate": 305,
        "minecraft:diamond_chestplate": 2,
        "minecraft:pointed_dripstone": 8,
        "minecraft:spruce_door": 2,
        "minecraft:gunpowder": 9,
        "minecraft:chest": 4,
        "minecraft:netherrack": 1,
        "minecraft:gravel": 66,
        "minecraft:light_gray_wool": 1,
        "minecraft:tuff": 47,
        "minecraft:polished_deepslate": 1,
        "minecraft:leaf_litter": 228,
        "minecraft:phantom_membrane": 1,
        "minecraft:birch_log": 268,
        "minecraft:shield": 3,
        "minecraft:lapis_lazuli": 90,
        "minecraft:spider_eye": 1,
        "minecraft:spruce_stairs": 18,
        "minecraft:dark_oak_log": 53,
        "minecraft:ominous_bottle": 2,
        "minecraft:diorite": 26,
        "minecraft:copper_horse_armor": 1,
        "minecraft:oak_planks": 189,
        "minecraft:crafting_table": 9,
        "minecraft:raw_copper": 22,
        "minecraft:oak_sapling": 496,
        "minecraft:stone_brick_stairs": 2,
        "minecraft:rotten_flesh": 47,
        "minecraft:beef": 138,
        "minecraft:apple": 36,
        "minecraft:cobblestone_slab": 2,
        "minecraft:oak_slab": 34,
        "minecraft:gray_wool": 9
      },
      "minecraft:crafted": {
        "minecraft:diamond_boots": 1,
        "minecraft:arrow": 24,
        "minecraft:book": 50,
        "minecraft:iron_chestplate": 1,
        "minecraft:glass_pane": 128,
        "minecraft:stick": 40,
        "minecraft:oak_fence": 24,
        "minecraft:cooked_porkchop": 136,
        "minecraft:iron_helmet": 1,
        "minecraft:diamond_axe": 2,
        "minecraft:iron_block": 16,
        "minecraft:diamond_pickaxe": 1,
        "minecraft:chest": 9,
        "minecraft:bookshelf": 16,
        "minecraft:air": 0,
        "minecraft:bow": 1,
        "minecraft:bucket": 1,
        "minecraft:oak_stairs": 200,
        "minecraft:dark_oak_planks": 212,
        "minecraft:diamond_shovel": 1,
        "minecraft:glass": 81,
        "minecraft:cobblestone_slab": 36,
        "minecraft:oak_trapdoor": 2,
        "minecraft:oak_planks": 1200,
        "minecraft:enchanting_table": 1,
        "minecraft:iron_shovel": 1,
        "minecraft:redstone_block": 31,
        "minecraft:cooked_chicken": 21,
        "minecraft:birch_planks": 68,
        "minecraft:hopper": 2,
        "minecraft:stone_pickaxe": 1,
        "minecraft:cooked_mutton": 148,
        "minecraft:spruce_door": 3,
        "minecraft:iron_boots": 1,
        "minecraft:wooden_pickaxe": 1,
        "minecraft:spruce_slab": 18,
        "minecraft:oak_fence_gate": 1,
        "minecraft:cooked_beef": 136,
        "minecraft:oak_door": 6,
        "minecraft:oak_slab": 264,
        "minecraft:diamond_chestplate": 1,
        "minecraft:diamond_sword": 1,
        "minecraft:paper": 156,
        "minecraft:raw_iron": 153,
        "minecraft:furnace": 10,
        "minecraft:black_bed": 1,
        "minecraft:iron_ingot": 153,
        "minecraft:dark_oak_slab": 18,
        "minecraft:raw_iron_block": 14,
        "minecraft:crafting_table": 6,
        "minecraft:torch": 16,
        "minecraft:spruce_stairs": 208,
        "minecraft:shield": 3,
        "minecraft:stone_axe": 1,
        "minecraft:spruce_planks": 484,
        "minecraft:iron_pickaxe": 2,
        "minecraft:iron_axe": 1,
        "minecraft:iron_leggings": 1
      }
    }
  }
];
const LAST_UPDATED = "2026-05-09 23:23:02";

const totalSrvKills = RAW_PLAYERS.reduce((s,p) => {
  const c = p.stats['minecraft:custom'] || {};
  return s + (c['minecraft:mob_kills'] || 0);
}, 0);
const totalSrvDeaths = RAW_PLAYERS.reduce((s,p) => {
  const c = p.stats['minecraft:custom'] || {};
  return s + (c['minecraft:deaths'] || 0);
}, 0);
const SRV_AVG = {
  kills: Math.round(totalSrvKills / Math.max(1, RAW_PLAYERS.length)),
  deaths: Math.round(totalSrvDeaths / Math.max(1, RAW_PLAYERS.length))
};

const PLAYERS = RAW_PLAYERS.map(raw => {
  const s = raw.stats || {};
  const k  = s['minecraft:killed']    || {};
  const kb = s['minecraft:killed_by'] || {};
  const m  = s['minecraft:mined']     || {};
  const c  = s['minecraft:custom']    || {};
  
  const drop = s['minecraft:dropped'] || {};
  const craft = s['minecraft:crafted'] || {};
  const broken = s['minecraft:broken'] || {};
  const used = s['minecraft:used'] || {};
  const picked = s['minecraft:picked_up'] || {};

    let play_time_raw = c['minecraft:play_time'] || 0;
    if (raw.name === "Better_Ansh") {
      play_time_raw = 130 * 72000;
    }

    let p = {
      uuid: raw.uuid,
      name: raw.name,
      team: getTeam(raw.name),
      killed_obj: k,        
      killed_by_obj: kb,    
      mined_obj: m,         
      dropped_obj: drop,
      crafted_obj: craft,
      broken_obj: broken,
      used_obj: used,
      picked_obj: picked,
      play_time_hrs: parseFloat((play_time_raw / 72000).toFixed(1)),
      deaths: c['minecraft:deaths'] || 0,
      player_kills: c['minecraft:player_kills'] || 0,
      total_mob_kills: c['minecraft:mob_kills'] || 0,
      blocks_mined: Object.values(m).reduce((a,b)=>a+b, 0),
      damage_dealt: c['minecraft:damage_dealt'] || 0,
      damage_taken: c['minecraft:damage_taken'] || 0,
      walk_km: parseFloat(((c['minecraft:walk_one_cm'] || 0) / 100000).toFixed(2)),
      sprint_km: parseFloat(((c['minecraft:sprint_one_cm'] || 0) / 100000).toFixed(2)),
      swim_km: parseFloat(((c['minecraft:swim_one_cm'] || 0) / 100000).toFixed(2)),
      climb_km: parseFloat(((c['minecraft:climb_one_cm'] || 0) / 100000).toFixed(2)),
      fly_km: parseFloat(((c['minecraft:fly_one_cm'] || 0) / 100000).toFixed(2)),
      sleep_in_bed: c['minecraft:sleep_in_bed'] || 0
    };

  p.kd = p.deaths > 0 ? parseFloat((p.total_mob_kills / p.deaths).toFixed(2)) : p.total_mob_kills;
  p.bas_score = calculateBAS(p);
  p.playstyle = detectPlaystyle(p);
  p.insights = generateInsights(p, SRV_AVG);
  p.history = generateFullHistory(p);
  p.achievements = checkAchievements(p);

  if (p.bas_score > 100000) p.rank = { title: "Legend", class: "rank-legend", nxt: null };
  else if (p.bas_score > 50000) p.rank = { title: "God Tier", class: "rank-god", nxt: 100000 };
  else if (p.bas_score > 10000) p.rank = { title: "Pro", class: "rank-pro", nxt: 50000 };
  else if (p.bas_score > 2000) p.rank = { title: "Veteran", class: "rank-vet", nxt: 10000 };
  else if (p.bas_score > 500) p.rank = { title: "Average", class: "rank-avg", nxt: 2000 };
  else p.rank = { title: "Noob", class: "rank-noob", nxt: 500 };

  return p;
});

PLAYERS.forEach(p1 => {
  let closest = null;
  let minDiff = Infinity;
  PLAYERS.forEach(p2 => {
    if(p1.uuid !== p2.uuid) {
      let diff = Math.abs(p1.bas_score - p2.bas_score);
      if(diff < minDiff) { minDiff = diff; closest = p2.name; }
    }
  });
  p1.rival = closest;
});

function calculateBAS(p) {
  let score = 0;
  score += (p.player_kills * 10);
  score += (p.total_mob_kills * 2);
  score += (p.blocks_mined * 0.01);
  score -= p.deaths;
  return Math.max(0, Math.round(score));
}

function detectPlaystyle(p) {
  if (p.player_kills > 50) return "Executioner | PvP Legend";
  if (p.total_mob_kills > 5000) return "Slayer | Monster Hunter";
  if (p.blocks_mined > 50000) return "Miner | Deepslate Devourer";
  return "Adventurer | Newcomer";
}

function generateInsights(p, avg) {
  let ins = [];
  if (p.kd > 5) ins.push({ type: 'good', text: "Elite combat performance." });
  if (p.deaths > avg.deaths) ins.push({ type: 'bad', text: "High death count compared to average." });
  return ins;
}

function generateFullHistory(p) {
  return { labels: ['Day 1', 'Day 2', 'Day 3', 'Today'], kills: [0, 10, 20, p.total_mob_kills], kd: [0, 1, 1.5, p.kd] };
}

function checkAchievements(p) { return []; }
