// =========================================================================
// BETTER_ANSH DASHBOARD - V3 DATA ENGINE
// =========================================================================

// TEAMS CONFIG
const TEAMS = {
  a: { name: "Team Alpha", short: "T-A", members: ["godxankit", "better_ansh", "adavya2193", "ansh gamer1988", "bettet_ansh"] },
  b: { name: "Team Beta", short: "T-B", members: ["kunal2010", "nitish_gamer45", "harshisop13", "deadly_kunal", "harsh"] }
};

function getTeam(name) {
  let lower = name.toLowerCase().replace('.', '');
  return TEAMS.b.members.includes(lower) ? 'b' : 'a';
}

const RAW_PLAYERS = [
  {
    "name": ".Harshisop13",
    "uuid": "00000000-0000-0000-0009-01f39b4bb6e8",
    "stats": {
      "minecraft:killed_by": {
        "minecraft:zombie": 1
      },
      "minecraft:killed": {
        "minecraft:pillager": 1,
        "minecraft:horse": 6,
        "minecraft:chicken": 12,
        "minecraft:sheep": 11,
        "minecraft:pig": 11,
        "minecraft:cow": 9
      },
      "minecraft:crafted": {
        "minecraft:stone_sword": 1,
        "minecraft:copper_boots": 1,
        "minecraft:polished_deepslate_stairs": 75,
        "minecraft:cooked_chicken": 8,
        "minecraft:birch_planks": 100,
        "minecraft:stone_pickaxe": 1,
        "minecraft:cooked_mutton": 17,
        "minecraft:iron_chestplate": 1,
        "minecraft:iron_boots": 3,
        "minecraft:stick": 28,
        "minecraft:cooked_beef": 9,
        "minecraft:copper_chestplate": 1,
        "minecraft:oak_slab": 126,
        "minecraft:cooked_porkchop": 22,
        "minecraft:iron_helmet": 2,
        "minecraft:diamond_axe": 1,
        "minecraft:chest": 7,
        "minecraft:diamond_pickaxe": 1,
        "minecraft:diamond_sword": 1,
        "minecraft:air": 0,
        "minecraft:bucket": 1,
        "minecraft:oak_stairs": 96,
        "minecraft:iron_ingot": 99,
        "minecraft:copper_ingot": 19,
        "minecraft:torch": 20,
        "minecraft:birch_slab": 54,
        "minecraft:polished_deepslate_slab": 24,
        "minecraft:stone_axe": 1,
        "minecraft:copper_helmet": 1,
        "minecraft:oak_planks": 300,
        "minecraft:diamond_spear": 1,
        "minecraft:iron_pickaxe": 1,
        "minecraft:iron_shovel": 2,
        "minecraft:iron_sword": 1,
        "minecraft:fishing_rod": 1,
        "minecraft:iron_axe": 1,
        "minecraft:iron_leggings": 2
      },
      "minecraft:used": {
        "minecraft:stone_axe": 108,
        "minecraft:diamond_sword": 54,
        "minecraft:water_bucket": 3,
        "minecraft:diamond_pickaxe": 263,
        "minecraft:cooked_mutton": 2,
        "minecraft:furnace": 3,
        "minecraft:cooked_porkchop": 15,
        "minecraft:torch": 8,
        "minecraft:dirt": 16,
        "minecraft:fishing_rod": 2,
        "minecraft:iron_shovel": 123,
        "minecraft:salmon_bucket": 1,
        "minecraft:stone_sword": 56,
        "minecraft:polished_deepslate_stairs": 58,
        "minecraft:oak_log": 46,
        "minecraft:cobblestone": 69,
        "minecraft:oak_stairs": 13,
        "minecraft:polished_deepslate_slab": 27,
        "minecraft:diamond_axe": 113,
        "minecraft:stripped_oak_log": 29,
        "minecraft:bucket": 5,
        "minecraft:crafting_table": 1,
        "minecraft:chest": 7,
        "minecraft:oak_planks": 115,
        "minecraft:white_bed": 2,
        "minecraft:stone_pickaxe": 114
      },
      "minecraft:custom": {
        "minecraft:time_since_rest": 64477,
        "minecraft:leave_game": 4,
        "minecraft:damage_taken": 1094,
        "minecraft:mob_kills": 50,
        "minecraft:time_since_death": 148778,
        "minecraft:interact_with_furnace": 73,
        "minecraft:sleep_in_bed": 7,
        "minecraft:total_world_time": 149625,
        "minecraft:swim_one_cm": 18977,
        "minecraft:crouch_one_cm": 10541,
        "minecraft:deaths": 1,
        "minecraft:climb_one_cm": 100,
        "minecraft:interact_with_stonecutter": 5,
        "minecraft:fish_caught": 1,
        "minecraft:interact_with_crafting_table": 16,
        "minecraft:walk_one_cm": 358565,
        "minecraft:walk_under_water_one_cm": 3740,
        "minecraft:play_time": 149625,
        "minecraft:damage_dealt": 4935,
        "minecraft:jump": 2094,
        "minecraft:drop": 13,
        "minecraft:bell_ring": 23,
        "minecraft:sprint_one_cm": 254720,
        "minecraft:open_chest": 29,
        "minecraft:fall_one_cm": 62813,
        "minecraft:fly_one_cm": 387833,
        "minecraft:walk_on_water_one_cm": 6128,
        "minecraft:sneak_time": 4528
      },
      "minecraft:dropped": {
        "minecraft:iron_axe": 1,
        "minecraft:cooked_chicken": 1,
        "minecraft:iron_shovel": 1,
        "minecraft:iron_helmet": 1,
        "minecraft:iron_chestplate": 1,
        "minecraft:copper_ingot": 2,
        "minecraft:iron_leggings": 1,
        "minecraft:iron_sword": 1,
        "minecraft:copper_chestplate": 1,
        "minecraft:iron_pickaxe": 1,
        "minecraft:cooked_mutton": 26,
        "minecraft:iron_boots": 1,
        "minecraft:salmon_bucket": 1
      },
      "minecraft:picked_up": {
        "minecraft:dirt": 124,
        "minecraft:cobblestone": 245,
        "minecraft:brown_wool": 1,
        "minecraft:polished_deepslate_slab": 9,
        "minecraft:white_bed": 3,
        "minecraft:stripped_oak_log": 29,
        "minecraft:leather": 15,
        "minecraft:bone": 8,
        "minecraft:salmon_bucket": 1,
        "minecraft:polished_deepslate": 112,
        "minecraft:oak_stairs": 12,
        "minecraft:coal": 86,
        "minecraft:cooked_mutton": 19,
        "minecraft:oak_log": 212,
        "minecraft:cod": 1,
        "minecraft:furnace": 3,
        "minecraft:birch_log": 25,
        "minecraft:diamond": 14,
        "minecraft:wheat_seeds": 2,
        "minecraft:egg": 1,
        "minecraft:pink_wool": 1,
        "minecraft:porkchop": 36,
        "minecraft:stick": 4,
        "minecraft:birch_sapling": 1,
        "minecraft:poppy": 1,
        "minecraft:cooked_beef": 13,
        "minecraft:white_wool": 8,
        "minecraft:feather": 9,
        "minecraft:oak_planks": 3,
        "minecraft:chicken": 11,
        "minecraft:cooked_porkchop": 13,
        "minecraft:crafting_table": 2,
        "minecraft:iron_axe": 1,
        "minecraft:raw_copper": 19,
        "minecraft:copper_chestplate": 1,
        "minecraft:oak_sapling": 5,
        "minecraft:iron_ingot": 29,
        "minecraft:raw_iron": 2,
        "minecraft:beef": 18,
        "minecraft:polished_deepslate_stairs": 1,
        "minecraft:apple": 2,
        "minecraft:mutton": 18,
        "minecraft:gray_wool": 1,
        "minecraft:iron_chestplate": 1
      },
      "minecraft:mined": {
        "minecraft:oak_stairs": 13,
        "minecraft:dirt": 2,
        "minecraft:dandelion": 1,
        "minecraft:birch_leaves": 4,
        "minecraft:coal_ore": 86,
        "minecraft:grass_block": 119,
        "minecraft:oak_planks": 1,
        "minecraft:cobblestone": 1,
        "minecraft:white_bed": 3,
        "minecraft:short_grass": 45,
        "minecraft:polished_deepslate_stairs": 2,
        "minecraft:oak_leaves": 8,
        "minecraft:furnace": 3,
        "minecraft:crafting_table": 2,
        "minecraft:birch_log": 25,
        "minecraft:polished_deepslate_slab": 11,
        "minecraft:oak_log": 59,
        "minecraft:stripped_oak_log": 29,
        "minecraft:iron_ore": 3,
        "minecraft:copper_ore": 5,
        "minecraft:stone": 257
      }
    }
  },
  {
    "name": "Nitish_gamer45",
    "uuid": "1cd7e03e-a260-35ca-88d7-e776003394c7",
    "stats": {
      "minecraft:killed": {
        "minecraft:horse": 1,
        "minecraft:cow": 2
      },
      "minecraft:crafted": {
        "minecraft:smooth_stone": 4,
        "minecraft:deepslate_tile_stairs": 37,
        "minecraft:tuff_brick_stairs": 34,
        "minecraft:cobblestone_stairs": 3
      },
      "minecraft:used": {
        "minecraft:iron_axe": 165,
        "minecraft:cobbled_deepslate": 96,
        "minecraft:cooked_mutton": 5,
        "minecraft:apple": 2,
        "minecraft:iron_pickaxe": 110,
        "minecraft:copper_chestplate": 1,
        "minecraft:dirt": 12,
        "minecraft:cooked_chicken": 1,
        "minecraft:oak_log": 161,
        "minecraft:cobblestone": 173,
        "minecraft:oak_door": 2,
        "minecraft:iron_shovel": 239
      },
      "minecraft:custom": {
        "minecraft:interact_with_crafting_table": 7,
        "minecraft:time_since_rest": 22258,
        "minecraft:walk_one_cm": 187163,
        "minecraft:leave_game": 1,
        "minecraft:mob_kills": 3,
        "minecraft:damage_taken": 123,
        "minecraft:play_time": 74489,
        "minecraft:damage_dealt": 490,
        "minecraft:jump": 550,
        "minecraft:time_since_death": 74489,
        "minecraft:drop": 8,
        "minecraft:interact_with_furnace": 18,
        "minecraft:sprint_one_cm": 190695,
        "minecraft:open_chest": 36,
        "minecraft:sleep_in_bed": 2,
        "minecraft:fall_one_cm": 9125,
        "minecraft:total_world_time": 74489,
        "minecraft:fly_one_cm": 115222,
        "minecraft:interact_with_stonecutter": 3
      },
      "minecraft:dropped": {
        "minecraft:copper_chestplate": 1,
        "minecraft:cooked_mutton": 7
      },
      "minecraft:picked_up": {
        "minecraft:egg": 2,
        "minecraft:iron_leggings": 1,
        "minecraft:dirt": 198,
        "minecraft:stick": 6,
        "minecraft:cobblestone": 110,
        "minecraft:iron_shovel": 1,
        "minecraft:leather": 4,
        "minecraft:iron_axe": 1,
        "minecraft:copper_chestplate": 1,
        "minecraft:oak_sapling": 2,
        "minecraft:cooked_chicken": 1,
        "minecraft:beef": 5,
        "minecraft:cobbled_deepslate": 39,
        "minecraft:iron_boots": 1,
        "minecraft:cooked_mutton": 26,
        "minecraft:oak_log": 266,
        "minecraft:copper_ingot": 2,
        "minecraft:iron_sword": 1,
        "minecraft:wheat_seeds": 12,
        "minecraft:oak_door": 1,
        "minecraft:iron_pickaxe": 1,
        "minecraft:iron_helmet": 1,
        "minecraft:iron_chestplate": 1
      },
      "minecraft:mined": {
        "minecraft:short_grass": 55,
        "minecraft:dirt": 12,
        "minecraft:oak_log": 148,
        "minecraft:grass_block": 186,
        "minecraft:cobblestone": 61,
        "minecraft:cobbled_deepslate": 39,
        "minecraft:oak_door": 1
      }
    }
  },
  {
    "name": "kunal2010",
    "uuid": "2ef7d0fb-36a6-3bc5-8bb1-b417ebdcf928",
    "stats": {
      "minecraft:killed_by": {
        "minecraft:creeper": 1
      },
      "minecraft:killed": {
        "minecraft:pillager": 5,
        "minecraft:skeleton": 4,
        "minecraft:iron_golem": 1,
        "minecraft:pig": 13,
        "minecraft:spider": 1,
        "minecraft:salmon": 3,
        "minecraft:zombie": 5,
        "minecraft:horse": 4,
        "minecraft:chicken": 5,
        "minecraft:enderman": 1,
        "minecraft:sheep": 19,
        "minecraft:cow": 8,
        "minecraft:wolf": 1
      },
      "minecraft:crafted": {
        "minecraft:diamond_boots": 1,
        "minecraft:iron_chestplate": 1,
        "minecraft:glass_pane": 32,
        "minecraft:leather_leggings": 3,
        "minecraft:stick": 72,
        "minecraft:cooked_porkchop": 19,
        "minecraft:diamond_axe": 2,
        "minecraft:iron_block": 2,
        "minecraft:diamond_pickaxe": 4,
        "minecraft:chest": 4,
        "minecraft:light_gray_dye": 1,
        "minecraft:air": 0,
        "minecraft:bucket": 1,
        "minecraft:oak_stairs": 20,
        "minecraft:diamond_shovel": 1,
        "minecraft:glass": 59,
        "minecraft:cobblestone_slab": 228,
        "minecraft:oak_planks": 200,
        "minecraft:polished_deepslate": 192,
        "minecraft:yellow_dye": 1,
        "minecraft:cooked_chicken": 6,
        "minecraft:stone_pickaxe": 2,
        "minecraft:cooked_mutton": 6,
        "minecraft:iron_boots": 1,
        "minecraft:smooth_stone": 28,
        "minecraft:white_wool": 1,
        "minecraft:wooden_pickaxe": 2,
        "minecraft:cooked_beef": 5,
        "minecraft:stonecutter": 1,
        "minecraft:blue_dye": 1,
        "minecraft:tuff_bricks": 8,
        "minecraft:diamond_chestplate": 1,
        "minecraft:diamond_sword": 2,
        "minecraft:polished_tuff": 8,
        "minecraft:emerald": 1,
        "minecraft:wheat": 82,
        "minecraft:raw_iron": 9,
        "minecraft:iron_ingot": 27,
        "minecraft:diamond_helmet": 1,
        "minecraft:bread": 36,
        "minecraft:stone": 35,
        "minecraft:crafting_table": 4,
        "minecraft:diamond_leggings": 1,
        "minecraft:white_bed": 4,
        "minecraft:magenta_dye": 1,
        "minecraft:stone_axe": 1,
        "minecraft:saddle": 1,
        "minecraft:iron_pickaxe": 1,
        "minecraft:iron_leggings": 1
      },
      "minecraft:used": {
        "minecraft:stone_axe": 91,
        "minecraft:leaf_litter": 26,
        "minecraft:cobbled_deepslate": 19,
        "minecraft:shield": 22,
        "minecraft:iron_pickaxe": 250,
        "minecraft:polished_deepslate": 83,
        "minecraft:iron_block": 2,
        "minecraft:diamond_sword": 144,
        "minecraft:diamond_shovel": 490,
        "minecraft:pink_wool": 1,
        "minecraft:rotten_flesh": 7,
        "minecraft:water_bucket": 46,
        "minecraft:wooden_axe": 5,
        "minecraft:diamond_pickaxe": 1580,
        "minecraft:cooked_mutton": 3,
        "minecraft:glass": 4,
        "minecraft:glass_pane": 32,
        "minecraft:cooked_porkchop": 12,
        "minecraft:bread": 3,
        "minecraft:dirt": 28,
        "minecraft:chicken": 1,
        "minecraft:diorite": 3,
        "minecraft:cobblestone_slab": 163,
        "minecraft:wooden_pickaxe": 7,
        "minecraft:oak_log": 65,
        "minecraft:cooked_chicken": 8,
        "minecraft:cobblestone": 139,
        "minecraft:gray_wool": 1,
        "minecraft:oak_stairs": 20,
        "minecraft:stonecutter": 1,
        "minecraft:cooked_beef": 6,
        "minecraft:diamond_axe": 507,
        "minecraft:bucket": 46,
        "minecraft:crafting_table": 5,
        "minecraft:chest": 4,
        "minecraft:oak_planks": 32,
        "minecraft:white_bed": 8,
        "minecraft:sugar_cane": 4,
        "minecraft:stone_pickaxe": 94,
        "minecraft:pointed_dripstone": 3
      },
      "minecraft:broken": {
        "minecraft:stone_axe": 1,
        "minecraft:iron_pickaxe": 1,
        "minecraft:diamond_pickaxe": 1
      },
      "minecraft:custom": {
        "minecraft:time_since_rest": 28009,
        "minecraft:talked_to_villager": 17,
        "minecraft:leave_game": 1,
        "minecraft:damage_taken": 1955,
        "minecraft:mob_kills": 72,
        "minecraft:time_since_death": 264225,
        "minecraft:interact_with_furnace": 112,
        "minecraft:sleep_in_bed": 5,
        "minecraft:swim_one_cm": 32608,
        "minecraft:total_world_time": 270748,
        "minecraft:crouch_one_cm": 11454,
        "minecraft:deaths": 1,
        "minecraft:climb_one_cm": 594,
        "minecraft:interact_with_stonecutter": 3,
        "minecraft:traded_with_villager": 2,
        "minecraft:damage_blocked_by_shield": 4010,
        "minecraft:interact_with_crafting_table": 64,
        "minecraft:walk_one_cm": 635246,
        "minecraft:walk_under_water_one_cm": 6255,
        "minecraft:damage_dealt": 10151,
        "minecraft:play_time": 270748,
        "minecraft:jump": 4670,
        "minecraft:drop": 234,
        "minecraft:bell_ring": 12,
        "minecraft:sprint_one_cm": 427934,
        "minecraft:open_chest": 90,
        "minecraft:fall_one_cm": 120573,
        "minecraft:fly_one_cm": 909941,
        "minecraft:walk_on_water_one_cm": 29563,
        "minecraft:sneak_time": 7126
      },
      "minecraft:dropped": {
        "minecraft:cobblestone": 59,
        "minecraft:oak_planks": 57,
        "minecraft:porkchop": 4,
        "minecraft:oxeye_daisy": 1,
        "minecraft:cobbled_deepslate": 266,
        "minecraft:poppy": 1,
        "minecraft:iron_ingot": 4,
        "minecraft:dripstone_block": 11,
        "minecraft:diamond": 14,
        "minecraft:stone_pickaxe": 2,
        "minecraft:azure_bluet": 2,
        "minecraft:cooked_chicken": 4,
        "minecraft:oak_log": 287,
        "minecraft:diamond_pickaxe": 1,
        "minecraft:dandelion": 8,
        "minecraft:chicken": 2,
        "minecraft:furnace": 1,
        "minecraft:string": 4,
        "minecraft:diamond_sword": 3,
        "minecraft:stick": 10,
        "minecraft:arrow": 3,
        "minecraft:crafting_table": 1,
        "minecraft:polished_deepslate": 112,
        "minecraft:gunpowder": 1,
        "minecraft:wooden_axe": 1,
        "minecraft:stone_axe": 2,
        "minecraft:iron_pickaxe": 1,
        "minecraft:mutton": 5,
        "minecraft:cooked_porkchop": 11
      },
      "minecraft:picked_up": {
        "minecraft:cobblestone": 788,
        "minecraft:polished_deepslate_slab": 1,
        "minecraft:flint": 8,
        "minecraft:white_bed": 5,
        "minecraft:sugar_cane": 4,
        "minecraft:leather": 13,
        "minecraft:bone": 9,
        "minecraft:redstone": 55,
        "minecraft:water_bucket": 1,
        "minecraft:stone_pickaxe": 3,
        "minecraft:wooden_axe": 3,
        "minecraft:diamond": 116,
        "minecraft:granite": 17,
        "minecraft:white_banner": 1,
        "minecraft:glow_ink_sac": 7,
        "minecraft:porkchop": 26,
        "minecraft:salmon": 2,
        "minecraft:stick": 14,
        "minecraft:black_wool": 1,
        "minecraft:chicken": 5,
        "minecraft:cooked_porkchop": 17,
        "minecraft:arrow": 11,
        "minecraft:iron_axe": 1,
        "minecraft:iron_ingot": 11,
        "minecraft:cooked_chicken": 2,
        "minecraft:raw_iron": 100,
        "minecraft:cobbled_deepslate": 980,
        "minecraft:diamond_chestplate": 1,
        "minecraft:pointed_dripstone": 15,
        "minecraft:hay_block": 12,
        "minecraft:raw_gold": 33,
        "minecraft:allium": 1,
        "minecraft:stone_axe": 3,
        "minecraft:dandelion": 9,
        "minecraft:wheat": 8,
        "minecraft:mutton": 32,
        "minecraft:gunpowder": 2,
        "minecraft:iron_chestplate": 1,
        "minecraft:dirt": 210,
        "minecraft:brown_wool": 2,
        "minecraft:gravel": 39,
        "minecraft:azure_bluet": 2,
        "minecraft:dripstone_block": 23,
        "minecraft:tuff": 73,
        "minecraft:polished_deepslate": 3,
        "minecraft:oxeye_daisy": 2,
        "minecraft:leaf_litter": 26,
        "minecraft:coal": 54,
        "minecraft:oak_log": 397,
        "minecraft:grass_block": 1,
        "minecraft:sand": 108,
        "minecraft:furnace": 1,
        "minecraft:wheat_seeds": 63,
        "minecraft:shield": 2,
        "minecraft:lapis_lazuli": 67,
        "minecraft:iron_pickaxe": 3,
        "minecraft:pumpkin": 6,
        "minecraft:iron_leggings": 1,
        "minecraft:diamond_sword": 2,
        "minecraft:ominous_bottle": 1,
        "minecraft:diorite": 26,
        "minecraft:wooden_pickaxe": 1,
        "minecraft:poppy": 2,
        "minecraft:cooked_beef": 10,
        "minecraft:feather": 1,
        "minecraft:white_wool": 15,
        "minecraft:oak_planks": 101,
        "minecraft:crafting_table": 2,
        "minecraft:raw_copper": 4,
        "minecraft:oak_sapling": 12,
        "minecraft:andesite": 31,
        "minecraft:rotten_flesh": 10,
        "minecraft:beef": 13,
        "minecraft:polished_deepslate_stairs": 1,
        "minecraft:apple": 2,
        "minecraft:cobblestone_slab": 2,
        "minecraft:string": 8,
        "minecraft:raw_iron_block": 1,
        "minecraft:obsidian": 9,
        "minecraft:cornflower": 1,
        "minecraft:iron_helmet": 1,
        "minecraft:gray_wool": 1
      },
      "minecraft:mined": {
        "minecraft:granite": 16,
        "minecraft:bush": 14,
        "minecraft:dandelion": 4,
        "minecraft:pumpkin": 6,
        "minecraft:coal_ore": 54,
        "minecraft:diorite": 26,
        "minecraft:oak_planks": 43,
        "minecraft:cobblestone": 127,
        "minecraft:hay_block": 10,
        "minecraft:sugar_cane": 2,
        "minecraft:white_bed": 4,
        "minecraft:gravel": 48,
        "minecraft:short_grass": 425,
        "minecraft:oak_leaves": 82,
        "minecraft:polished_deepslate": 3,
        "minecraft:crafting_table": 1,
        "minecraft:deepslate_redstone_ore": 3,
        "minecraft:oxeye_daisy": 2,
        "minecraft:obsidian": 4,
        "minecraft:copper_ore": 1,
        "minecraft:raw_iron_block": 1,
        "minecraft:tall_grass": 58,
        "minecraft:pointed_dripstone": 9,
        "minecraft:tall_seagrass": 1,
        "minecraft:dirt": 24,
        "minecraft:andesite": 31,
        "minecraft:grass_block": 178,
        "minecraft:cobbled_deepslate": 7,
        "minecraft:tuff": 72,
        "minecraft:deepslate": 652,
        "minecraft:sand": 108,
        "minecraft:seagrass": 3,
        "minecraft:cobblestone_slab": 2,
        "minecraft:poppy": 1,
        "minecraft:deepslate_lapis_ore": 4,
        "minecraft:deepslate_diamond_ore": 112,
        "minecraft:cornflower": 2,
        "minecraft:deepslate_iron_ore": 92,
        "minecraft:dripstone_block": 1,
        "minecraft:oak_log": 388,
        "minecraft:allium": 1,
        "minecraft:iron_ore": 10,
        "minecraft:lapis_ore": 6,
        "minecraft:stone": 641
      }
    }
  },
  {
    "name": "Harsh",
    "uuid": "41cae289-aab6-3d0e-ab10-4533b37cb8a0",
    "stats": {
      "minecraft:crafted": {
        "minecraft:stick": 12,
        "minecraft:wooden_axe": 1,
        "minecraft:oak_planks": 44,
        "minecraft:crafting_table": 1
      },
      "minecraft:used": {
        "minecraft:wooden_axe": 1,
        "minecraft:crafting_table": 1
      },
      "minecraft:custom": {
        "minecraft:interact_with_crafting_table": 1,
        "minecraft:time_since_rest": 6020,
        "minecraft:walk_one_cm": 4205,
        "minecraft:leave_game": 1,
        "minecraft:damage_taken": 150,
        "minecraft:play_time": 6020,
        "minecraft:jump": 84,
        "minecraft:time_since_death": 6020,
        "minecraft:drop": 8,
        "minecraft:sprint_one_cm": 10607,
        "minecraft:fall_one_cm": 2225,
        "minecraft:total_world_time": 6020,
        "minecraft:fly_one_cm": 18356,
        "minecraft:walk_on_water_one_cm": 904,
        "minecraft:crouch_one_cm": 152,
        "minecraft:sneak_time": 146
      },
      "minecraft:picked_up": {
        "minecraft:oak_log": 11,
        "minecraft:wooden_axe": 1,
        "minecraft:stick": 10,
        "minecraft:oak_planks": 31,
        "minecraft:crafting_table": 2
      },
      "minecraft:dropped": {
        "minecraft:crafting_table": 2,
        "minecraft:oak_planks": 62,
        "minecraft:wooden_axe": 2,
        "minecraft:stick": 20
      },
      "minecraft:mined": {
        "minecraft:short_grass": 1,
        "minecraft:crafting_table": 1,
        "minecraft:oak_log": 5
      }
    }
  },
  {
    "name": "Better_Ansh",
    "uuid": "93c37127-b993-3dbb-8005-865c96a3e98c",
    "stats": {
      "minecraft:killed_by": {
        "minecraft:creeper": 1,
        "minecraft:zombie": 2
      },
      "minecraft:killed": {
        "minecraft:pillager": 2,
        "minecraft:slime": 7,
        "minecraft:skeleton": 7,
        "minecraft:iron_golem": 1,
        "minecraft:pig": 48,
        "minecraft:wandering_trader": 1,
        "minecraft:spider": 6,
        "minecraft:zombie": 16,
        "minecraft:horse": 6,
        "minecraft:trader_llama": 1,
        "minecraft:creeper": 2,
        "minecraft:zombie_villager": 1,
        "minecraft:chicken": 20,
        "minecraft:sheep": 39,
        "minecraft:cow": 34
      },
      "minecraft:crafted": {
        "minecraft:diamond_boots": 1,
        "minecraft:cooked_chicken": 21,
        "minecraft:birch_planks": 4,
        "minecraft:stone_pickaxe": 1,
        "minecraft:cooked_mutton": 45,
        "minecraft:iron_chestplate": 1,
        "minecraft:iron_boots": 1,
        "minecraft:stick": 16,
        "minecraft:wooden_pickaxe": 1,
        "minecraft:oak_fence_gate": 1,
        "minecraft:cooked_beef": 58,
        "minecraft:oak_door": 6,
        "minecraft:oak_slab": 30,
        "minecraft:oak_fence": 6,
        "minecraft:cooked_porkchop": 93,
        "minecraft:iron_helmet": 1,
        "minecraft:diamond_axe": 1,
        "minecraft:iron_block": 16,
        "minecraft:diamond_pickaxe": 1,
        "minecraft:chest": 2,
        "minecraft:diamond_chestplate": 1,
        "minecraft:diamond_sword": 1,
        "minecraft:air": 0,
        "minecraft:raw_iron": 153,
        "minecraft:bucket": 1,
        "minecraft:furnace": 7,
        "minecraft:iron_ingot": 54,
        "minecraft:diamond_shovel": 1,
        "minecraft:cobblestone_slab": 36,
        "minecraft:raw_iron_block": 14,
        "minecraft:crafting_table": 4,
        "minecraft:oak_trapdoor": 2,
        "minecraft:shield": 3,
        "minecraft:stone_axe": 1,
        "minecraft:oak_planks": 72,
        "minecraft:iron_pickaxe": 2,
        "minecraft:redstone_block": 31,
        "minecraft:iron_axe": 1,
        "minecraft:iron_leggings": 1
      },
      "minecraft:used": {
        "minecraft:stone_axe": 64,
        "minecraft:oak_fence": 1,
        "minecraft:oak_trapdoor": 1,
        "minecraft:iron_axe": 23,
        "minecraft:iron_leggings": 2,
        "minecraft:cobbled_deepslate": 121,
        "minecraft:shield": 59,
        "minecraft:iron_pickaxe": 169,
        "minecraft:polished_deepslate": 1,
        "minecraft:iron_block": 1,
        "minecraft:diamond_sword": 135,
        "minecraft:diamond_shovel": 203,
        "minecraft:water_bucket": 82,
        "minecraft:diamond_pickaxe": 579,
        "minecraft:cooked_mutton": 6,
        "minecraft:furnace": 16,
        "minecraft:cooked_porkchop": 20,
        "minecraft:dirt": 141,
        "minecraft:lava_bucket": 1,
        "minecraft:diorite": 6,
        "minecraft:cobblestone_slab": 38,
        "minecraft:wooden_pickaxe": 20,
        "minecraft:oak_log": 18,
        "minecraft:cooked_chicken": 9,
        "minecraft:cobblestone": 32,
        "minecraft:diamond_chestplate": 2,
        "minecraft:cooked_beef": 18,
        "minecraft:diamond_axe": 484,
        "minecraft:bucket": 83,
        "minecraft:crafting_table": 10,
        "minecraft:chest": 1,
        "minecraft:iron_helmet": 1,
        "minecraft:oak_planks": 4,
        "minecraft:oak_fence_gate": 1,
        "minecraft:white_bed": 2,
        "minecraft:sugar_cane": 3,
        "minecraft:stone_pickaxe": 107,
        "minecraft:oak_door": 6
      },
      "minecraft:broken": {
        "minecraft:shield": 1
      },
      "minecraft:custom": {
        "minecraft:time_since_rest": 139730,
        "minecraft:leave_game": 4,
        "minecraft:damage_taken": 4973,
        "minecraft:mob_kills": 194,
        "minecraft:time_since_death": 139688,
        "minecraft:interact_with_furnace": 142,
        "minecraft:sleep_in_bed": 2,
        "minecraft:swim_one_cm": 70809,
        "minecraft:total_world_time": 245282,
        "minecraft:crouch_one_cm": 33617,
        "minecraft:deaths": 5,
        "minecraft:climb_one_cm": 57,
        "minecraft:damage_blocked_by_shield": 8406,
        "minecraft:interact_with_crafting_table": 61,
        "minecraft:walk_one_cm": 344673,
        "minecraft:walk_under_water_one_cm": 31058,
        "minecraft:damage_dealt": 21978,
        "minecraft:play_time": 245282,
        "minecraft:jump": 4752,
        "minecraft:drop": 19,
        "minecraft:sprint_one_cm": 561642,
        "minecraft:open_chest": 62,
        "minecraft:fall_one_cm": 153515,
        "minecraft:fly_one_cm": 892829,
        "minecraft:walk_on_water_one_cm": 46657,
        "minecraft:sneak_time": 18643
      },
      "minecraft:dropped": {
        "minecraft:iron_axe": 1,
        "minecraft:iron_ingot": 33,
        "minecraft:oak_planks": 6,
        "minecraft:wooden_axe": 1,
        "minecraft:iron_chestplate": 1,
        "minecraft:gray_wool": 1,
        "minecraft:shield": 1,
        "minecraft:bone": 8,
        "minecraft:diamond_sword": 1,
        "minecraft:salmon_bucket": 1
      },
      "minecraft:picked_up": {
        "minecraft:iron_block": 3,
        "minecraft:cobblestone": 141,
        "minecraft:white_bed": 2,
        "minecraft:sugar_cane": 9,
        "minecraft:leather": 40,
        "minecraft:bone": 11,
        "minecraft:redstone": 547,
        "minecraft:salmon_bucket": 1,
        "minecraft:lead": 3,
        "minecraft:water_bucket": 1,
        "minecraft:wooden_axe": 1,
        "minecraft:diamond": 68,
        "minecraft:slime_ball": 14,
        "minecraft:granite": 9,
        "minecraft:white_banner": 1,
        "minecraft:glow_ink_sac": 7,
        "minecraft:porkchop": 104,
        "minecraft:stick": 110,
        "minecraft:black_wool": 2,
        "minecraft:chicken": 22,
        "minecraft:diamond_boots": 1,
        "minecraft:cooked_porkchop": 5,
        "minecraft:arrow": 8,
        "minecraft:iron_axe": 1,
        "minecraft:iron_ingot": 166,
        "minecraft:cooked_chicken": 4,
        "minecraft:raw_iron": 253,
        "minecraft:cobbled_deepslate": 279,
        "minecraft:diamond_chestplate": 1,
        "minecraft:pointed_dripstone": 8,
        "minecraft:hay_block": 15,
        "minecraft:raw_gold": 89,
        "minecraft:dandelion": 2,
        "minecraft:mutton": 57,
        "minecraft:gunpowder": 5,
        "minecraft:chest": 1,
        "minecraft:dirt": 226,
        "minecraft:light_gray_wool": 1,
        "minecraft:diamond_pickaxe": 2,
        "minecraft:dripstone_block": 12,
        "minecraft:tuff": 47,
        "minecraft:polished_deepslate": 1,
        "minecraft:leaf_litter": 13,
        "minecraft:coal": 184,
        "minecraft:oak_log": 190,
        "minecraft:birch_log": 7,
        "minecraft:furnace": 11,
        "minecraft:wheat_seeds": 16,
        "minecraft:oak_door": 7,
        "minecraft:shield": 1,
        "minecraft:lapis_lazuli": 64,
        "minecraft:iron_pickaxe": 3,
        "minecraft:iron_leggings": 1,
        "minecraft:diamond_sword": 3,
        "minecraft:ominous_bottle": 1,
        "minecraft:diorite": 13,
        "minecraft:birch_sapling": 4,
        "minecraft:cooked_beef": 12,
        "minecraft:copper_horse_armor": 1,
        "minecraft:feather": 18,
        "minecraft:white_wool": 27,
        "minecraft:oak_planks": 52,
        "minecraft:crafting_table": 6,
        "minecraft:oak_sapling": 139,
        "minecraft:andesite": 2,
        "minecraft:rotten_flesh": 26,
        "minecraft:beef": 62,
        "minecraft:apple": 20,
        "minecraft:cobblestone_slab": 2,
        "minecraft:string": 10,
        "minecraft:raw_iron_block": 3,
        "minecraft:obsidian": 15,
        "minecraft:iron_helmet": 2,
        "minecraft:gray_wool": 6
      },
      "minecraft:mined": {
        "minecraft:granite": 10,
        "minecraft:bush": 3,
        "minecraft:chest": 1,
        "minecraft:dandelion": 1,
        "minecraft:coal_ore": 52,
        "minecraft:diorite": 13,
        "minecraft:oak_planks": 6,
        "minecraft:cobblestone": 26,
        "minecraft:hay_block": 15,
        "minecraft:sugar_cane": 6,
        "minecraft:white_bed": 2,
        "minecraft:short_grass": 64,
        "minecraft:oak_leaves": 12,
        "minecraft:furnace": 11,
        "minecraft:polished_deepslate": 1,
        "minecraft:crafting_table": 5,
        "minecraft:birch_log": 7,
        "minecraft:deepslate_redstone_ore": 86,
        "minecraft:leaf_litter": 8,
        "minecraft:oxeye_daisy": 1,
        "minecraft:obsidian": 5,
        "minecraft:raw_iron_block": 3,
        "minecraft:tall_grass": 46,
        "minecraft:pointed_dripstone": 1,
        "minecraft:dirt": 17,
        "minecraft:gold_ore": 10,
        "minecraft:birch_leaves": 1,
        "minecraft:andesite": 3,
        "minecraft:grass_block": 214,
        "minecraft:deepslate_gold_ore": 48,
        "minecraft:cobbled_deepslate": 7,
        "minecraft:tuff": 39,
        "minecraft:deepslate": 155,
        "minecraft:cobblestone_slab": 1,
        "minecraft:deepslate_lapis_ore": 6,
        "minecraft:deepslate_diamond_ore": 56,
        "minecraft:deepslate_iron_ore": 162,
        "minecraft:iron_block": 3,
        "minecraft:dripstone_block": 4,
        "minecraft:oak_log": 187,
        "minecraft:iron_ore": 36,
        "minecraft:stone": 110,
        "minecraft:oak_door": 6
      }
    }
  }
];
const LAST_UPDATED = "2026-05-08 19:33:08";

const totalSrvKills = RAW_PLAYERS.reduce((s,p) => {
  const c = p.stats['minecraft:custom'] || {};
  return s + (c['minecraft:mob_kills'] || 0);
}, 0);
const totalSrvDeaths = RAW_PLAYERS.reduce((s,p) => {
  const c = p.stats['minecraft:custom'] || {};
  return s + (c['minecraft:deaths'] || 0);
}, 0);
const SRV_AVG = {
  kills: Math.round(totalSrvKills / Math.max(1, RAW_PLAYERS.length)),
  deaths: Math.round(totalSrvDeaths / Math.max(1, RAW_PLAYERS.length))
};

const PLAYERS = RAW_PLAYERS.map(raw => {
  const s = raw.stats || {};
  const k  = s['minecraft:killed']    || {};
  const kb = s['minecraft:killed_by'] || {};
  const m  = s['minecraft:mined']     || {};
  const c  = s['minecraft:custom']    || {};
  
  const drop = s['minecraft:dropped'] || {};
  const craft = s['minecraft:crafted'] || {};
  const broken = s['minecraft:broken'] || {};
  const used = s['minecraft:used'] || {};
  const picked = s['minecraft:picked_up'] || {};

    let play_time_raw = c['minecraft:play_time'] || 0;
    if (raw.name === "Better_Ansh") {
      play_time_raw = 130 * 72000;
    }

    let p = {
      uuid: raw.uuid,
      name: raw.name,
      team: getTeam(raw.name),
      killed_obj: k,        
      killed_by_obj: kb,    
      mined_obj: m,         
      dropped_obj: drop,
      crafted_obj: craft,
      broken_obj: broken,
      used_obj: used,
      picked_obj: picked,
      play_time_hrs: parseFloat((play_time_raw / 72000).toFixed(1)),
      deaths: c['minecraft:deaths'] || 0,
      player_kills: c['minecraft:player_kills'] || 0,
      total_mob_kills: c['minecraft:mob_kills'] || 0,
      blocks_mined: Object.values(m).reduce((a,b)=>a+b, 0),
      damage_dealt: c['minecraft:damage_dealt'] || 0,
      damage_taken: c['minecraft:damage_taken'] || 0,
      walk_km: parseFloat(((c['minecraft:walk_one_cm'] || 0) / 100000).toFixed(2)),
      sprint_km: parseFloat(((c['minecraft:sprint_one_cm'] || 0) / 100000).toFixed(2)),
      swim_km: parseFloat(((c['minecraft:swim_one_cm'] || 0) / 100000).toFixed(2)),
      climb_km: parseFloat(((c['minecraft:climb_one_cm'] || 0) / 100000).toFixed(2)),
      fly_km: parseFloat(((c['minecraft:fly_one_cm'] || 0) / 100000).toFixed(2)),
      sleep_in_bed: c['minecraft:sleep_in_bed'] || 0
    };

  p.kd = p.deaths > 0 ? parseFloat((p.total_mob_kills / p.deaths).toFixed(2)) : p.total_mob_kills;
  p.bas_score = calculateBAS(p);
  p.playstyle = detectPlaystyle(p);
  p.insights = generateInsights(p, SRV_AVG);
  p.history = generateFullHistory(p);
  p.achievements = checkAchievements(p);

  if (p.bas_score > 100000) p.rank = { title: "Legend", class: "rank-legend", nxt: null };
  else if (p.bas_score > 50000) p.rank = { title: "God Tier", class: "rank-god", nxt: 100000 };
  else if (p.bas_score > 10000) p.rank = { title: "Pro", class: "rank-pro", nxt: 50000 };
  else if (p.bas_score > 2000) p.rank = { title: "Veteran", class: "rank-vet", nxt: 10000 };
  else if (p.bas_score > 500) p.rank = { title: "Average", class: "rank-avg", nxt: 2000 };
  else p.rank = { title: "Noob", class: "rank-noob", nxt: 500 };

  return p;
});

PLAYERS.forEach(p1 => {
  let closest = null;
  let minDiff = Infinity;
  PLAYERS.forEach(p2 => {
    if(p1.uuid !== p2.uuid) {
      let diff = Math.abs(p1.bas_score - p2.bas_score);
      if(diff < minDiff) { minDiff = diff; closest = p2.name; }
    }
  });
  p1.rival = closest;
});

function calculateBAS(p) {
  let score = 0;
  score += (p.player_kills * 10);
  score += (p.total_mob_kills * 2);
  score += (p.blocks_mined * 0.01);
  score -= p.deaths;
  return Math.max(0, Math.round(score));
}

function detectPlaystyle(p) {
  if (p.player_kills > 50) return "Executioner | PvP Legend";
  if (p.total_mob_kills > 5000) return "Slayer | Monster Hunter";
  if (p.blocks_mined > 50000) return "Miner | Deepslate Devourer";
  return "Adventurer | Newcomer";
}

function generateInsights(p, avg) {
  let ins = [];
  if (p.kd > 5) ins.push({ type: 'good', text: "Elite combat performance." });
  if (p.deaths > avg.deaths) ins.push({ type: 'bad', text: "High death count compared to average." });
  return ins;
}

function generateFullHistory(p) {
  return { labels: ['Day 1', 'Day 2', 'Day 3', 'Today'], kills: [0, 10, 20, p.total_mob_kills], kd: [0, 1, 1.5, p.kd] };
}

function checkAchievements(p) { return []; }
